### ISSUE TITLE
Consider refactoring eval functions in Ops.cpp

### ISSUE THREAD

**Issue by ghpvnist** [openxla/stablehlo#1000]
Ops for whose implementations not written in [Element.cpp](https://github.com/openxla/stablehlo/blob/main/stablehlo/reference/Element.cpp) cannot be reused by other ops because the eval functions have to take in the op as an argument. This would pose problems in the future with Batch*ops which require using a combination of other ops.

Recently in DynamicUpdateSliceOp's interpreter #998, I also faced an issue where I'm not able to use ClampOp since I need to construct a tensor for min and max, which cannot be created with ease. Introducing an API to create tensors out of primitive types and/or with shape (defaulting to scalar) would also be useful.

**Comment by sdasgup3** [comment]
One option could be convert the `eval(AddOp, Tensor lhs, ...)` to `eval_add(Type returnType, Tensor ..)`. Anyways the `eval` is currently not overloaded, so we are not adding more declaration by doing that. 

Let us keep the alternative thoughts coming.

**Comment by sdasgup3** [comment]
Following is the list of those 17 ops whose spec has with dependencies written in sub-bullets. 
The dependencies are mostly elementwise ops and others (all_reduce, broadcast_in_dim, clamp, concatenate, constant, dot_general, pad, reduce, reshape, slice, transpose) 


* all_gather
  - concatenate
* all_reduce
  - reduce
* all_to_all
  - slice, concatenate
* batch_norm_grad
  - reduce, constant, broadcast_in_dim, divide, subtract, sqrt, add, multiply
* batch_norm_inference
  - broadcast_in_dim, subtract, sqrt, add, divide, add, multiply
* Batch_norm_training
  - reduce, constant, broadcast_in_dim, divide, subtract, multiply
* convolution
  - pad, dot_general, Slice, Concatenate
* dot_general
  - transpose, slice, reshape, reduce
* dynamic_Slice
  - clamp
* dynamic_update_slice
  - clamp
* log_plus_one
  - log
* logistic
  - divide, add, exponentiation
* maximum
  - or
* minimum
  - and
* reduceScatter
  - all_reduce, slice
* reduce_window
  - pad, slice
* select_andScatter
  - reduce_window, reduce

**Comment by sdasgup3** [comment]
The proposal is to make the changes in two steps:
1. To replace `eval(AddOp, ...)` with `eval_add(Type returnType, ...)`.
2. Sharing the shape inference code from `TypeInference.cpp`:  Identify  the code section in the selected `infer<Op>` functions (were Op is one of `concatenate, dot_general, reduce, slice`) in `TypeInference.cpp`  which can be re-used by the reference implementation  and hoist those code sections as functions in `TypeInference.cpp`, to be shared between reference-implementation and type-inference.

**Comment by ghpvnist** [comment]
One op that's missed is that ConvolutionOp also uses ReverseOp as described in the [spec](https://github.com/openxla/stablehlo/blob/main/docs/spec.md#semantics-24). I will have a PR to address this op as well.
