### ISSUE TITLE
Use camel case for variable names in Ops.cpp

### ISSUE THREAD

**Issue by zhouxin913** [openxla/stablehlo#1030]
Example:
`for (auto it = result.index_begin(); it != result.index_end(); ++it)`

**Comment by burmako** [comment]
`foo_begin()` and `foo_end()` are actually a special case that is exempted from the camel case policy: https://llvm.org/docs/CodingStandards.html#name-types-functions-variables-and-enumerators-properly, so I think the use of snake case for them is justified. Do we have other examples of non-camel-case variables in the codebase?

**Comment by zhouxin913** [comment]
None, and I'm closing this bug without any fix.
