### ISSUE TITLE
Consider aligning VhloAttrs.td with the spec

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#1047]
Having completed another round of reviews of #849, I was thinking about the overall design of VHLO. We've been working on it since October - it went through several iterations of design, and several big pull requests - so it felt like it's a good time to reflect.

Even though it's a lot of code, I'm quite pleased with how things are going. Our high-level design is fairly approachable - we've got a dedicated dialect, three crisp passes that operate on it and the rest is implementation details. E.g. if needed, each pass can be rewritten from scratch with little effect on the rest of the system.

Then I started thinking about the VHLO dialect aka our serialization schema:
  * Ops look fine - in some areas, the opset is all over the place (especially around the Dynamism and Not in HLO categories), which creates essential complexity of the domain, so it's fine that things are messy right now. We have tickets to clean them up.
  * Types look fine too - in 849, they mostly correspond 1:1 to the spec (except for encodings, index and quantization, but we have tickets to clean all that up as well through dynamism, quantization and sparsity work).
  * However, I am somewhat concerned about attrs. In 849, they represent a mixture of custom attributes and forked upstream attributes, and I find it rather hard to wrap my head around that.

Just like with types, I think that we should aim at 1:1 correspondence with the spec. Concretely, towards that end I'd like to propose to:
  1. Get rid of all `VHLO_ConvDimensionNumbersAttr` and friends. I think that grouping of the elementary attrs into bigger attrs is pretty incidental as far as serialization format goes, so I would propose to break all of them down, just like the spec does.
  2. Rename `VHLO_DenseIntOrFPElementsAttr` to `VHLO_TensorAttr` to be aligned with the spec. Keeping the forked name is understandable, but I think that alignment with the spec is more important.
  3. Drop `VHLO_FlatSymbolRefAttr` and use `VHLO_StringAttr` instead.
  4. Drop `VHLO_UnitAttr` and use `VHLO_IntegerAttr` instead.

**Comment by GleasonK** [comment]
Also consider scoping 
https://github.com/openxla/stablehlo/pull/849/files/0ccd3220810030d7e968fcf5b2cd419d009c10fd#r1096258167
