### ISSUE TITLE
Populate conformance suite with "interesting" test cases

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#1152]
Our current methodology for testing the reference implementation involves writing a minimal amount of tests (https://github.com/openxla/stablehlo/blob/main/docs/reference_checklist.md), but for a conformance suite we'll likely want to write "interesting" tests that cover potentially surprising behavior, even if strictly speaking these tests don't increase coverage of the codebase. Let's think about how this could look like.

**Comment by GleasonK** [comment]
Covered by `testdata` which will evolve on an as-needed basis (i.e. add dynamism tests and quantized tests).
