### ISSUE TITLE
Align our Check dialect with IREE's Check dialect

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#1219]
To follow up on #1218, it would be great to align [our Check dialect](https://github.com/openxla/stablehlo/blob/main/stablehlo/tests/CheckOps.td) with [IREE's Check dialect](https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Modules/Check/IR/CheckOps.td), so that the conformance suite could also be used verbatim as a test suite for IREE.

**Comment by GleasonK** [comment]
This is a great idea. Consideration should be given to single-sourcing the check dialect if possible (if dependencies allow).

I want to also note that I like IREE's distinction between `expect*` and `expect*_const`. It would be useful in StableHLO to have a variant that can accept two operands, especially for our generated test data which stores expected results separately for readability.
