### ISSUE TITLE
Add the specification and interpreter for BroadcastInDimOp

### ISSUE THREAD

**Issue by sdasgup3** [openxla/stablehlo#122]
### Request description

Add the specification and implement the interpreter for  `stablehlo.broadcast` op.

**Comment by sdasgup3** [comment]
https://github.com/openxla/stablehlo/pull/167 is created which will set the stage for stride based tensor element address. We expect the broadcast implementation to be no extra copy of element: Rather the strides will be used to point to the original storage (before applying broadcast) to refer to the broadcasted elements.

**Comment by burmako** [comment]
This is part of the ongoing work on speccing control flow, data movement and reduction ops. Will be worked on this week.
