### ISSUE TITLE
Also run CHLO tests as part of the compatibility suite

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#1233]
At the moment, these tests are skipped because: 1) we don't provide compatibility guarantees for CHLO, 2) CHLO needs to be decomposes to StableHLO to obtain guarantees, 3) the chlo-legalize-to-hlo pass currently lives in the MLIR-HLO repo.

**Comment by GleasonK** [comment]
Closed by #1256. No CHLO tests point to this issue anymore, all have more specific issues.
