### ISSUE TITLE
32-bit erf is inaccurate for x > 1

### ISSUE THREAD

**Issue by jakevdp** [openxla/stablehlo#1238]
### What happened?

First reported in https://github.com/google/jax/issues/14717; 32-bit `erf` is inaccurate for large inputs. 

Digging in, it looks like the 32-bit Erf implmentation is here: https://github.com/tensorflow/tensorflow/blob/cfaf6285f4a84dd350c83b05d19f8b4c267b241e/tensorflow/compiler/xla/mlir_hlo/mhlo/transforms/chlo_legalize_to_hlo/chlo_legalize_to_hlo.cc#L527

Rather than using a direct polynomial approximation, it should probably switch between `erf` and `1 - erfc` depending on the size of the input, similar to how the 64-bit version is implemented just above: https://github.com/tensorflow/tensorflow/blob/cfaf6285f4a84dd350c83b05d19f8b4c267b241e/tensorflow/compiler/xla/mlir_hlo/mhlo/transforms/chlo_legalize_to_hlo/chlo_legalize_to_hlo.cc#L386

### Steps to reproduce your issue

Short reproduction in JAX
```python
>>> import jax, scipy
>>> x = 3.9004288
>>> print(jax.lax.erf(x), scipy.special.erf(x))
1.0000001 0.999999965327526
```
Using `erfc` provides better results:
```python
>>> print(1 - jax.lax.erfc(x))
0.99999994
```

### Version information

jax/jaxlib version 0.4.4, which pins the XLA source via the tensorflow hash here: https://github.com/google/jax/blob/jaxlib-v0.4.4/WORKSPACE#L13

**Comment by atondwal** [comment]
Looks like this bug is also present in tensorflow/tensorflow/compiler/xla/client/lib/math.cc (which is where these functions were ported from. I'll take a crack at a fix in the morning.

**Comment by atondwal** [comment]
Technically this is a bug in tensorflow/mlir-hlo, so I'm moving this issue there: https://github.com/tensorflow/mlir-hlo/issues/62

**Comment by atondwal** [comment]
(that bug is now fixed)

**Comment by rmlarsen** [comment]
I'm sorry I didn't look at  this bug before.
The title of the bug is very misleading. The difference between 1.0000001 0.999999965327526 is just slightly more than 1 ULP, and both are within 1 ULP of the correctly rounded answer, i.e. moth are very accurate. It's unfortunate that the XLA implementation does not correctly clamp the result to [-1:1], but it is certainly very accurate.
