### ISSUE TITLE
Decide what to do with build warnings

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#125]
MLIR-HLO has a problem with build warning spew (https://github.com/tensorflow/mlir-hlo/issues/43), and we're starting to have an issue with this as well. One possibility to address this would be to compile with `-Werror`.

**Comment by GleasonK** [comment]
I'm a fan of strict builds. High lint level and error on warnings. We have a relatively small codebase currently, so probably a good plan to get these practices in place before it grows and number of errors balloons.

Only issues in the past that I've run into with high lint level / error on warnings is upstream dependencies introducing warnings and compiler upgrades. As long as we have a procedure in place to temporarily disable warnings so long as there is an open issue, and cite that issue # in a code comment todo, shouldn't be an issue.
