### ISSUE TITLE
Fork upstream bytecode reader/writer into our repo

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#1282]
As the MLIR bytecode format is starting to evolve towards providing stability guarantees, we can expect breaking changes in bytecode format/reader/writer (see https://github.com/llvm/llvm-project/issues/61176 for details). Let's fork the relevant upstream code to make sure that portable artifacts are shielded from potential breakages.

**Comment by GleasonK** [comment]
A part of this will likely involve storing some version information in a header so we know what reader/writer to dispatch a file to.

**Comment by GleasonK** [comment]
> But for that case it is simply one of not bumping your git rev.

So for forward compatibility, a user would revert to an older revision of StableHLO and build with related MLIR commit, then serialize on that version? If so, this doesn't work well for clients that continuously bump revision, like JAX. Similarly there has been discussion of users who want the option of forward compatibility, but can also toggle it off when using newer ops.

**Comment by jpienaar** [comment]
Those are forward compatibility on ops and not bytecode AFAIK. So that's independent.

Have you actually reached out and had a discussion with the community? E.g., we are having quite a good one with folks from 4 different companies there already who are actively contributing code. Our other collaborators there are doing dialect downgrades, so not using an older revision. If folks want toggling for certain ops, that becomes a property of the dialect specific downgrade mechanism.

**Comment by burmako** [comment]
Thank you for inviting to collaborate more closely! We've been keeping track of the LLVM ticket linked above, as well as the in-progress patches in MLIR upstream (e.g. https://reviews.llvm.org/D146555), and it's great to know that there's an active ongoing discussion. How do we participate? E.g. is there a Discourse thread or perhaps this could be a good ODM topic?

In the meanwhile, we're also looking for a short-term solution that would allow to ship StableHLO-based artifacts with compatibility guarantees today (this is something that some stakeholders are strongly interested in). While the long-term discussion in MLIR upstream is ongoing, the easiest stopgap solution involves forking which is why it was proposed in this ticket.

This probably wasn't apparent from the way the ticket is phrased, but we're looking at forking only as a stopgap solution until the MLIR upstream conversations conclude. I believe this is consistent with how we discussed this at the bytecode versioning roundtable at the LLVM Developers' Meeting in November. This is what we captured in the meeting notes from the event, although maybe we misunderstood something.

Anyway, thank you @jpienaar and @joker-eph for reaching out! Sounds like some of our plans around compatibility ended up being surprising for you, and that wasn't the intent. Looking forward to furthering our alignment on this - as you might've seen in our GTC talk, we're big fans of MLIR bytecode, and it would be great to work on it together.

**Comment by GleasonK** [comment]
Thanks @joker-eph, @jpienaar, and @burmako for the feedback. I agree that StableHLO should work together with MLIR upstream to align on a long-term solution (#1490). At the same time there is a need for short term solution in StableHLO as we already have users relying on [StableHLO compatibility guarantees](https://github.com/openxla/stablehlo/blob/main/docs/compatibility.md).

I think we can do both: Have a short-term breakglass plan for StableHLO, where we temporarily fork upstream reader/writer to maintain compatibility in case MLIR upstream accidentally or deliberately breaks forward/backward compatibility, working to resolve any issues upstream (i.e. don't fork code unless absolutely necessary, work to resolve compatibility issues upstream, similar to how https://reviews.llvm.org/D146555 resolved existing forward compatibility issues), while discussing/contributing upstream towards a long-term communal solution.

Both short-term and long-term solutions will require better incompatibility detection. This is something StableHLO can help contribute immediately. We already have backward compatibility tests for the StableHLO repo, and will be adding CI including forward compatibility testing shortly (#1318, #1489) - will share a forward compatibility RFC in openxla-discuss this week. Perhaps a compatibility test similar to what LLVM bitcode has could live in MLIR upstream for detection of forward / backward incompatible changes. Given the state of upstream bytecode, this test could be _allowed_ to break, but even then it would serve as a detection mechanism to ensure compatibility isn't unintentionally broken.

In parallel, we will work to increase our presence in MLIR upstream discussions and describe StableHLO requirements for serialization, also contributing to development when possible. This will be important as discussion of _what_ the forward/backward compatibility guarantees offered upstream could be.

Closing this ticket, as remaining work described above is captured by the mentioned issues.

**Comment by joker-eph** [comment]
I read your post twice, but I still don't understand the plan? 
I have strong concerns about any attempt to fork of the MLIR serialization in OpenXLA, and I can't tell if you plan to do this or not at the moment.

**Comment by GleasonK** [comment]
The proposed plan is to not fork upstream reader/writer unless this is absolutely needed to uphold [the StableHLO compatibility guarantees](https://github.com/openxla/stablehlo/blob/main/docs/compatibility.md).

In the near future, we are planning to share compatibility requirements from StableHLO stakeholders on LLVM Discourse ([#1490](https://github.com/openxla/stablehlo/issues/1490)), with the goal to ideally work out an upstream solution and take part in compatibility requirements discussions.

In exceptional cases, e.g. when an MLIR patch accidentally breaks compatibility for a long period of time or if MLIR forward / backward compatibility window ends up being smaller than what StableHLO offers, we will need to do _something_ to maintain our compatibility guarantees. I am very open to feedback on what this "something" could be. My current thinking is that we would temporarily fork either the reader (backward incompat) or writer (forward incompat) and try to resolve these issues upstream, at which point we can delete our temporary fork.

**Comment by joker-eph** [comment]
> In exceptional cases, e.g. when an MLIR patch accidentally breaks compatibility for a long period of time

If this something is broken we should be able to detect it quickly and roll-back or fix it though? So « long period of time » to me means « we didn’t detect it », in which case either we’re not affecte or it is too late anyway and we need a fix upstream still (that is:  forking does not seem like a solution I can see helping here either)
