### ISSUE TITLE
Define next steps for using stablehlo/testdata in interpreter tests

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#1291]
To summarize the offline discussion:
  1) What tests can we enable already? (Partially answered by #1290).
  2) When will we be able to enable the rest of the tests?
  3) How should we update [the checklist](https://github.com/openxla/stablehlo/blob/main/docs/reference_checklist.md) now that we have all these tests in stablehlo/testdata?

**Comment by ghpvnist** [comment]
1. There are some floating-point precision issues we need to sort out before enabling the rest. However, we can enable all tests for Data Movement ops, for which if we run into issues, will look into them:
* broadcast_in_dim
* concatenate
* dynamic_slice
* dynamic_update_slice
* gather #1058
* pad
* reshape
* slice
* sort #1283 
* transpose

2. We are hoping to enable all tests soon. However, some issues -- 1) some tests include attributes we plan to remove, 2) currently unsupported ops, 3) tests mixed with supported and unsupported ops, 4) floating-precision issues, 5) currently supported attributes like `precision_config` or having preferred element type for DotGeneral and Convolution which are not yet implemented -- have to be solved before all tests are enabled. The exact ETA to enable all tests is TBD, but the next steps for doing so would be to update the testing infrastructure to better capture difference in precision, which is expected to finish by the end of Q1.

3. I plan to update the checklist to enable any tests that are passing, including floating-point tests as this issue has to do with current testing infrastructure and not with, say wrong implementation (which we may find by enabling these tests progressively).

**Comment by sdasgup3** [comment]
Some stats as of 03/08:
 - Total tests: 3329 
 - Enabled: 308 (All integer tests which are all passing)
 - Disabled: 3021
     - **Tests we could enable by 03/31: 1203 (ideally)** 
         - Out of 1203, 343 are int tests and the rest (860) are float/complex tests. 
         - Out of 1203, 332 are fully covered on 03/13, of which all except 15 are passing and hence they could be enabled right away.
             - The 15 tests failing because of precision mismatch (11) or other problems to be explored (4)

     - Not planned to be enable for Q1'23: 1818
         -  Out of 1818, 1116 are int tests and the rest (702) are float/complex tests.
         - These tests has the ops   `atan2, bitcast_convert, cbrt, complex, get_tuple_element, is_finite, round_nearest_afz, round_nearest_even, scatter, shift_left, sign,  popcnt, shift_right_arithmetic, shift_right_logical, exponential_minus_one, triangular_solve, log_plus_one` which are not focusing for Q1'2023.


  1) What tests can we enable already?
317 tests we can enable today. We will be publishing a PR for that. 

  2) When will we be able to enable the rest of the tests?
Whenever an op is added we should be running any disabled tests in testdata/  which can now be covered with the newly added operation. 

  3) How should we update [the checklist](https://github.com/openxla/stablehlo/blob/main/docs/reference_checklist.md) now that we have all these tests in stablehlo/testdata?

IMO,
While adding an op, run any disabled tests in testdata/  which can now be covered with the newly added operation. 
    -  If the tests pass, then we enable them. 
    - If it fails, then fix the test if the reason if other than precision mismatch. For precision mismatches, tag the test with `RUN-DISABLED(#1278)`, if not already tagged like that

**Comment by burmako** [comment]
"IMO, While adding an op, run any disabled tests in testdata/ which can now be covered with the newly added operation...". Sounds like a plan, and thank you for the analysis! Let's update the checklist to reflect that?

**Comment by ghpvnist** [comment]
As pointed out in #1775, we should also consider what to do with sign-based floating-point comparison when enhancing this comparator.

**Comment by ghpvnist** [comment]
There two remaining sets of disabled tests:
* Decomposable ops
* Floating-point mismatches

Some ops need to be decomposed using OpenXLA tooling described in [interpreter_status.md](https://github.com/openxla/stablehlo/blob/5e41e674af78da676652459c2dcf6a0d76e59ddb/docs/interpreter_status.md) before it can be interpreted (cholesky, triangular_solve, etc.). These tests are currently disabled but will be kept as data files for compiler authors to use as tests. These can be run using the OpenXLA tooling described in the reference interpreter documentation linked above. The transformations may accumulate additional floating-point rounding, but see below regarding precision.

Floating-point/numerics has been determined to be lower importance in the reference interpreter for now until there is a need proposed in the community. The FP tests will remain disabled and act as data files for backend authors.
