### ISSUE TITLE
Add Python API for serializing/deserializing portable artifacts

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#1301]
https://github.com/openxla/xla/pull/1424 provides a sketch.

**Comment by yongwww** [comment]
it would be great to enable python api to work with bytecode format

**Comment by GleasonK** [comment]
I'll take a closer look into python APIs in the coming days. We can get something figured out in StableHLO, I just need to put a bit of time into understanding the python api build infrastructure. But I agree, would be great to have this capability in python.

If there are any timelines or compatibility requirements you're working with let me know so we can do our best to accommodate!
