### ISSUE TITLE
Handle custom_call in --stablehlo-refine-shapes

### ISSUE THREAD

**Issue by GleasonK** [openxla/stablehlo#1351]
### What happened?

Custom call is not currently handled in MLIR shape refinement.

### Steps to reproduce your issue

The following appears in the result of shape refinement. Note that the output of the custom call is not updated.

```
%457 = stablehlo.custom_call @Sharding(%456) {mhlo.sharding = "{replicated}"} : (tensor<1x4x4xbf16>) -> ten     sor<1x?x4xbf16>
...
%491 = stablehlo.add %457, %490 : (tensor<1x?x4xbf16>, tensor<1x4x4xbf16>) -> tensor<1x4x4xbf16>
```

**Comment by burmako** [comment]
Custom calls are actually supported by shape refinement: #1169. Would that mechanism work for your use case?

**Comment by GleasonK** [comment]
Yes, https://github.com/openxla/stablehlo/pull/1169 is what is needed. I didn't realize this feature existed. Thanks!
