### ISSUE TITLE
A generic mechanism for shape refinement for custom calls

### ISSUE THREAD

**Issue by gnecula** [openxla/stablehlo#1367]
### Request description

Currently I am trying to use the `indices_of_shape_operands` attribute for the custom_call op to specify the shapes of the outputs as 1D tensor operands.

There are a couple of problems with this mechanism. First, shape refinement does not work today when the custom call returns a tuple. This could be fixed easily.

The real problem is that this mechanism forces the custom call target to take an extra operand, which likely has no use during the computation. Some of these custom call targets do take operands that are used in the computation and determine the output shape, but for the `indices_of_shape_operands` I am forced to add another operand just for shape refinement. Furthermore, this operand will be transferred to the device, which is a waste.

In some important use cases, I am now forced to change the custom call target in order to take this operand, even though after shape refinement it has no use. Changing the C++ targets is not easy because we need to keep the old code for backwards compatibility. We could write a pass that runs after shape refinement to rewrite dynamic_custom_call_target into custom_call_target, if the output shape is a constant, but this does not work in general because one would have to change the `backend_config` in some cases.

I propose a different, less intrusive mechanism. We can add a RefineShapeOp: `refine_shape(%a, %shape_operand)` that can be used for an operand `%a` with dynamic shapes to refine the shape with a 1d tensor `%shape_operand`. The rank of `%a` must be equal to the length of `%shape_operand`. During shape refinement the `shape_operand` will be a constant, or will have some constant elements, which will refine the shape of `%a`. 

The front-end will add this to the outputs of a custom call, and the shape refinement will have to flow the contraints to the producer of its operand.

This mechanism could be used for other ops that today need to take a shape operand only for the purpose of shape refinement, e.g., DynamicGatherOp (#690).

**Comment by gnecula** [comment]
One simpler solution is to agree that the operands marked by `indices_of_operand_shapes` are not actual arguments, they are removed from the argument list when the C++ call target is called. If the call target needs them, then they can be passed twice. They can be removed when legalizing to MHLO.

**Comment by burmako** [comment]
Started working on this in #1378. Once/if that PR is approved, it will be very easy to extend it to do what George is proposing in the second comment.
