### ISSUE TITLE
dot_general type constraints in spec are too strict

### ISSUE THREAD

**Issue by hawkinsp** [openxla/stablehlo#1439]
### What happened?

https://github.com/openxla/stablehlo/blob/main/docs/spec.md#dot_general
states that the LHS and RHS of a `dot_general` must have equal types. (Constraint C1)

This is stricter than what XLA already supports: XLA allows the LHS and RHS to have different types.

**Comment by ghpvnist** [comment]
Linking related issue as I've also pointed this out in #755

**Comment by sdasgup3** [comment]
Hi @hawkinsp 
Thanks for pointing to the issue. I agree that the constraint is too strict and (rightfully) not honored  by the current verifier. 
From [here](https://github.com/tensorflow/tensorflow/blob/49959d2f7d5e497edf90d6cdebc9afa3247234b7/tensorflow/compiler/xla/hlo/evaluator/hlo_evaluator_typed_visitor.h#L1411), hlo_verifier, and conversation of XLA/HLO experts, I realized that there are no particular constraints on the type of the operands and the result is as precise as if the operands were casted to the output type. 

As pointed by @ghpvnist, there is closely related concerns around the interpretation of the enum values value of precison config which governs at what precision the computation happens on those operations and at what precision the accumulation of results happens.    

So here is my proposal:
1. Remove the constraint from the spec.md
2. Clarify the spec.md with the interpretation of different operand types as part of https://github.com/openxla/stablehlo/issues/1354.

@hawkinsp Please let us know if this sounds right to you?

**Comment by sdasgup3** [comment]
From my offline conversation,  @hawkinsp is onboard with the proposal. Here is the [PR](https://github.com/openxla/stablehlo/pull/1445) removing the redundant constraint. With that let us close the current ticket to be superseded by the [action item](https://github.com/openxla/stablehlo/issues/755#issuecomment-1483590911) discussed in issue https://github.com/openxla/stablehlo/issues/755.

**Comment by sdasgup3** [comment]
Hi @hawkinsp 
As it turned out in the [conversation](https://github.com/openxla/stablehlo/pull/1445#discussion_r1183176358) that the "removing the constraint from the spec" cannot be isolated from addressing #755. Do you mind if we address the current issue once we have clarity on #755?

**Comment by sdasgup3** [comment]
From my offline discussion with @hawkinsp, let us revisit this as proposed above. Unassigning for now.
