### ISSUE TITLE
Agree on plan for when to increment API Version

### ISSUE THREAD

**Issue by GleasonK** [openxla/stablehlo#1456]
The [`getApiVersion`](https://github.com/openxla/stablehlo/blob/main/stablehlo/dialect/Version.h#L81-L83) method states that it is incremented on all C/C++/Python API changes. 

What this means is unclear, i.e. should it be incremented whenever ODS changes and a builder method changes? Probably not.

One possibility would be to only change on API changes to C/Python APIs in the `integrations/`. This number is most useful in Python, where users can say `call(x) if version == 2 else call(x, y)`. API changes of this sort would break the build in a compiled language.

**Comment by burmako** [comment]
Fixed in https://github.com/openxla/stablehlo/pull/1480.
