### ISSUE TITLE
Examples/Algorithm about stablehlo.scatter op

### ISSUE THREAD

**Issue by AmosLewis** [openxla/stablehlo#1476]
### What happened?

I am recently working on converting **torch to stablehlo** in torch-mlir project. I am stuck on the understanding of the **stablehlo.scatter op examples**. I find this op is quite complex and the examples are hard to understand. The lead of torch-mlir project [Ramiro Leal-Cavazos](https://github.com/ramiro050) point out that it would be good if I ask stablehlo folks directly. After checking the PR history, I found it was @sdasgup3 who added these examples https://github.com/openxla/stablehlo/pull/330. Would you mind giving me a more detailed explanation/specific examples about how this op works?
It would be better if you guys can show that in [stablehlo::scatter](https://github.com/openxla/stablehlo/blob/main/docs/spec.md#scatter) doc, what is the **update_index** / index space of updates[0] looks like. I also create an issue in torch-mlir project torch-mlir issues https://github.com/llvm/torch-mlir/issues/2069, anyone familiar with it can directly reply to me on that issue.

I tried to manually give exact values for scatter examples with my understanding of stablehlo.scatter op. But it will lead to a segfault when calling **scatter_indices[update_scatter_index]**. The following are the detailed examples I tried to derive the stablehlo.scatter algorithm. 

### Steps to reproduce your issue

```
input: 4 * 3 * 2
[[[0,1],[2,3],[4,5],[6,7]],
[[10,11],[12,13],[14,15], [16,17]],
[[20,21],[22,23],[24,25], [26,27]],]
updates: 2 * 3 * 2 * 2 i32
[
[[[100,101],[102,103]],[[200, 201],[202, 203]],[[300,301],[302,303]]],
[[[400,401],[402,403]],[[500,501],[502,503]],[[600,601],[602,603]]],
]
updates[0]: 3 * 2 * 2
[[[100,101],[102,103]],[[200, 201],[202, 203]],[[300,301],[302,303]]]
```
**Is this the index space of update[0] ???**
```
update_index:3 * 2 * 2 * 3
[[[[0,0,0],[0,0,1]],[[0,1,0],[0,1,1]]], [[[1,0,0], [1,0,1]],[[1,1,0], [1,1,1]]], [[[2,0,0],[2,0,1]],[[3,1,0],[3,1,1]]]]
```

**More formally, for all update_index from the index space of updates[0]:**
update_scatter_dims = [d for d in axes(updates[0]) and d not in update_window_dims].
update_window_dims: [2,3]
axes(updates[0]):[0,1,2] 
update_scatter_dims:[0,1]

**update_scatter_index = [update_index[d] for d in update_scatter_dims].**
```
update_index[0]: 2 * 2 * 3
[[[0,0,0],[0,0,1]],[[0,1,0],[0,1,1]]]
update_index[1]: 2 * 2 * 3
[[[1,0,0], [1,0,1]],[[1,1,0], [1,1,1]]]
update_scatter_index:2 * 2 * 2 * 3
[[[[0,0,0],[0,0,1]],[[0,1,0],[0,1,1]]],
[[[1,0,0], [1,0,1]],[[1,1,0], [1,1,1]]]]
scatter_indices: 2 * 3 * 2 i64
[[[],[1,0],[2,1]],
[[],[],[0,2],]]
```
rank(update_scatter_index) : 4

**start_index =
	1. scatter_indices[si0, ..., :, ..., siN] where si are individual elements in update_scatter_index and : is inserted at the index_vector_dim index, if index_vector_dim < rank(scatter_indices).**
	**2. [scatter_indices[update_scatter_index]] otherwise.**
index_vector_dim:2
rank(scatter_indices) : 4

**scatter_indices[update_scatter_index] :  SEGFAULT**
```
update_scatter_index: 3 * 2
[[0,1],[0,2],[1,2]]
start_index:
[[1,0],[2,1],[0,1]]
```

**Comment by sdasgup3** [comment]
Hi @AmosLewis 

Let me start with the example in the spec
```
// %input: [
//          [[1, 2], [3, 4], [5, 6], [7, 8]],
//          [[9, 10], [11, 12], [13, 14], [15, 16]],
//          [[17, 18], [19, 20], [21, 22], [23, 24]]
//         ]

// %scatter_indices: [[[0, 2], [1, 0], [2, 1]], [[0, 1], [1, 0], [2, 0]]]

// %update: [
//           [[[1, 1], [1, 1]], [[1, 1], [1, 1]], [[1, 1], [1, 1]]],
//           [[[1, 1], [1, 1]], [[1, 1], [1, 1]], [[1, 1], [1, 1]]]
//          ]
```

A few things to note:
1. shape of `input`: [3, 4, 2]
2. size(inputs) = size(updates) = size(results) = 1. The update[0] represents the single update argument we have. 
3. Given the shape of update[0] is [2,3,2,2], The index space of `updates[0]` has 24 (=2x3x2x2) entries. For example, `(0,0,0,0), (0,0,0,1), (0,0,1,0), (0,0,1,1), (0,1,0,0), (0,1,0,1), (0,1,1,0), (0,1,1,1), (0,2,0,0), ..., (1,2,1,1)`

Here is how the op works informally at a high level,

1. Initially the `results[0]` has the same values as `inputs[0]`
2. For each of the above mentioned index, U, in `updates[0]`, we find a result index, I, in `result[0]`. Say the value is `V`. Then the updated value of `results[0][I]` is update_computation(results[0][I], V)`.

Now, in order to convert a index `U` in the index space of `updates[0]` into an index `I` in the index space of `results[0]`, the  op uses extra parameters like `scatter_indices`, `scatter_dims_to_operand_dims`, `update_window_dims`, `inserted_window_dims`, and `index_vector_dim`. 


Before getting into the above conversion, let us note a few minor fixes in your presentation to get us on the same page.

>> input: 4 * 3 * 2
[
[[0,1],[2,3],[4,5],[6,7]],
[[10,11],[12,13],[14,15], [16,17]],
[[20,21],[22,23],[24,25], [26,27]],
]

The shape is [3,4,2]

>> Is this the index space of update[0] ???

I think what you are considering is the shape. Please see my comment above to get the index. 


With that fixes, let us see how the conversion happens. 

Let us chose an `update[0]` index, say [1,2,1,0]

Using the notations from the semantics section of the spec

1. update_scatter_dims = [0,1]]
2. update_scatter_index = [1,2]
3. start_index = [0,2]
4. full_window_index = [2, 0, 0]
5. update_window_index = [1,0]
6. full_window_index = [0,1,0].
7. result_index = [2, 0, 0] + [0, 1, 0] = [2, 1, 0]

`results[0][2,1,0] = update_compulation(results[0][2,1,0] /*old value*/,   updates[0][1,2,1,0]) = add(19, 1) = 20`

Please let me know if this makes sense now?

**Comment by AmosLewis** [comment]
`update[0] is [2,3,2,2]`
The update you give is 
```
// %update: [
//           [[[1, 1], [1, 1]], [[1, 1], [1, 1]], [[1, 1], [1, 1]]],
//           [[[1, 1], [1, 1]], [[1, 1], [1, 1]], [[1, 1], [1, 1]]]
//          ]
```
which is  [2,3,2,2]. So shouldn't the update[0] is [1,3,2,2]? @sdasgup3

**Comment by sdasgup3** [comment]
Hi @AmosLewis 

So `updates` is name of an operand for this op which is variadic, that is, the number of such operands is variable. In the spec we represent it as `size(updates) >= 1`. So if `n` such operands are provided, they can be referred to in the spec as as `updates[i], 0 <= i < n`. Per constraint `C3`, all such `updates` operands have the same shape.

The example in the spec (and also the one that I highlighted in my previous reply) is such that the variable count for `updates` operand is 1, `size(updates)` = 1, and that particular operand is referred to as `updates[0]`. `updates[0]`  has the shape `[2,3,2,2]`. 

```
// %update: [
//           [[[1, 1], [1, 1]], [[1, 1], [1, 1]], [[1, 1], [1, 1]]],
//           [[[1, 1], [1, 1]], [[1, 1], [1, 1]], [[1, 1], [1, 1]]]
//          ]
```

The `%update` SSA variable referred to in the example section (also quoted above) is the one referred in the spec as `updates[0]`. 

>> And you use updates[0] and update[0], I guess it is a typo and you mean the same thing?

You are right, I have updates my previous response to fix all those cases. 

>> size(inputs) = size(updates) = size(results) = 1

Like `updates`, `inputs` and `results` are also variadic and `size(inputs)` refers to the number of such `inputs` operands present in an instance of scatter op. Same with `results`. 

So given the same example as above
```
// %input: [
//          [[1, 2], [3, 4], [5, 6], [7, 8]],
//          [[9, 10], [11, 12], [13, 14], [15, 16]],
//          [[17, 18], [19, 20], [21, 22], [23, 24]]
//         ]

// %update: [
//           [[[1, 1], [1, 1]], [[1, 1], [1, 1]], [[1, 1], [1, 1]]],
//           [[[1, 1], [1, 1]], [[1, 1], [1, 1]], [[1, 1], [1, 1]]]
//          ]
```
Here `size(inputs) = size(updates)  = 1`. So there is one `inputs` operand, which is `inputs[0]`, and one `updates` operand, which is `updates[0]`, whos shapes are [3,4,2] and [2,3,2,2] resp.



Sorry for the confusion. Please let me know if that helps.

**Comment by AmosLewis** [comment]
@sdasgup3 Thanks. You explanation helps me a lot.  I try to use your examples to derive the algorithm again.

> Let us chose an updates[0] index, say [1,2,1,0]
> Using the notations from the semantics section of the spec
> update_scatter_dims = [0,1]]
> update_scatter_index = [1,2]
> start_index = [0,2]
> full_window_index = [2, 0, 0]
> update_window_index = [1,0]
> full_window_index = [0,1,0].
> result_index = [2, 0, 0] + [0, 1, 0] = [2, 1, 0]

After the start_index, I am stuck. There is still something that is unclear in the algorithm. 
Here is the step-by-step derive with examples. I bold each line of the algorithm. And right after each algorithm line, I give the spec examples with values.
```
inputs[0] 
= input: 3 * 4 *2
[
[[1, 2], [3, 4], [5, 6], [7, 8]],
[[9, 10], [11, 12], [13, 14], [15, 16]],
[[17, 18], [19, 20], [21, 22], [23, 24]]
]
```

```
updates[0] 
= update: 2*3*2*2 i32
= torch.tensor(
[ 
	[[[1, 1], [1, 1]], [[1, 1], [1, 1]], [[1, 1], [1, 1]]],
	[[[1, 1], [1, 1]], [[1, 1], [1, 1]],[[1, 1], [1, 1]]]
])
```


This the index space of update[0]:
```
update_indexes_tensor:2 * 3 * 2 * 2     *     4 
[
[[[[0, 0, 0, 0], [0, 0, 0, 1]], [[0, 0, 1, 0], [0, 0, 1, 1]]], [[[0, 1, 0, 0], [0, 1, 0, 1]], [[0, 1, 1, 0], [0, 1, 1, 1]]], [[[0, 2, 0, 0], [0, 2, 0, 1]], [[0, 2, 1, 0], [0, 2, 1, 1]]] ],
[[[[1, 0, 0, 0], [1, 0, 0, 1]], [[1, 0, 1, 0], [1, 0, 1, 1]]], [[[1, 1, 0, 0], [1, 1, 0, 1]], [[1, 1, 1, 0], [1, 1, 1, 1]]], [[[1, 2, 0, 0], [1, 2, 0, 1]], [[1, 2, 1, 0], [1, 2, 1, 1]]]],
]
```
In other words: update_indexes is consist of 24(=2x3x2x2) update_index, each update_index.shape=[4]


**More formally, for all update_index from the index space of updates[0]:**

update_scatter_dims = [d for d in axes(updates[0]) and d not in update_window_dims].
d = axes(updates[0]):[0,1,2,3] 
update_window_dims: [2,3]
update_scatter_dims:[0,1]


**update_scatter_index = [update_index[d] for d in update_scatter_dims].**

Let us choose an updates[0] index, say the chosen update_index = [1,2,1,0]
d = [0,1]
update_index[0] = 1
update_index[1] = 2
so 
	update_scatter_index = [1,2]



**start_index =
	1. scatter_indices[si0, ..., :, ..., siN] where si are individual elements in update_scatter_index and : is inserted at the index_vector_dim index, if index_vector_dim < rank(scatter_indices).
	2. [scatter_indices[update_scatter_index]] otherwise.**

rank(update_scatter_index) : 2
index_vector_dim = 2
scatter_indices: 2 * 3 * 2 i64
[
[ [0,2], [1,0], [2,1] ],
[ [0,1], [1,0], [0,2] ],
]
rank(scatter_indices) = 3
so 
	index_vector_dim < rank(scatter_indices)
so choose option 1
	start_index = scatter_indices[si0, ..., :, ..., siN] 
				= scatter_indices[1,2] 
				= [0,2]


**For do in axes(inputs[0]):
	1. full_start_index[do] = start_index[ds] if do = scatter_dims_to_operand_dims[ds].
	2. full_start_index[do] = 0 otherwise.**

do = axes(inputs[0]) = [0,1,2]
scatter_dims_to_operand_dims = [1,0]

do = 0
	What is ds ? @sdasgup3 
	If ds = [0,1]
	scatter_dims_to_operand_dims[0] = 1 != do

	what is full_start_index? @sdasgup3 
	full_start_index[0] = ?
do = 1 ?
do = 2 ?



The following is the algorithm line to be added more examples values.
**update_window_index = [update_index[d] for d in update_window_dims].**


**full_window_index = [oi0, ..., 0, ..., oiN] where oi are individual elements in update_window_index, and 0 is inserted at indices from inserted_window_dims.**


**result_index = add(full_start_index, full_window_index).**


Given that, results = exec(schedule, inputs), where:
**schedule is an implementation-defined permutation of the index space of updates[0].**

exec([update_index, ...], results) = exec([...], updated_results) where:
  1. updated_values = update_computation(results[:][result_index], updates[:][update_index]).
  2. updated_results is a copy of results with results[:][result_index] set to updated_values[:].
  3. If result_index is out of bounds for shape(results[:]), the behavior is implementation-defined.

**exec([], results) = results**

**Comment by sdasgup3** [comment]
Let us first have a look at a few relevant constrats

From 
```
(C11) size(scatter_dims_to_operand_dims)
 index_vector_dim
 rank(scatter_indices) ? dim(scatter_indices, index_vector_dim) : 1.
```

In the running example,
`size(scatter_dims_to_operand_dims)` =  dim(scatter_indices, index_vector_dim)  = 2`.
Also, `size(start_index) = dim(scatter_indices, index_vector_dim)` based on how `start_index` is computed. 

With that, let me attempt to elaborate what the following says,
```
For do in axes(inputs[0]): 
1. full_start_index[do] = start_index[ds] if do = scatter_dims_to_operand_dims[ds].
2. full_start_index[do] = 0 otherwise.
```

Informally, for each axis `do` in `axes(inputs[0])`, populate `full_start_index`  such that

1. `full_start_index[do] = start_index[ds]` if we find a `ds` such that `scatter_dims_to_operand_dims[ds]`. 
2. If we do not find such a `ds`, then full_start_index[do] = 0.

Let us continue with the example,
```
inputs[0].shape = [4,3,2]
do = axes(inputs[0]) = [0,1,2]
scatter_dims_to_operand_dims = [1,0]
start_index = [0, 2]
```

do = 0
Is there a `ds` such that  do = scatter_dims_to_operand_dims[ds]? Yes when ds == 1.
Then, we populate full_start_index[0] = start_index[1] = 2

do = 1
Is there a `ds` such that  do = scatter_dims_to_operand_dims[ds]? Yes when ds == 0.
Then, we populate full_start_index[1] = start_index[0] = 0

do = 2
Is there a `ds` such that  do = scatter_dims_to_operand_dims[ds]? No.
Then, we populate full_start_index[2] = 0

So we get the full_start_index = [2, 0, 0]

Hope that will clear the confusion.

**Comment by sdasgup3** [comment]
Hi @AmosLewis 
Please let me know what you think about the above explanation. Happy to help!

**Comment by AmosLewis** [comment]
> Hi @AmosLewis Please let me know what you think about the above explanation. Happy to help!

Thanks sandeep. This helps me a lot. I will give you a detailed response tomorrow.

**Comment by AmosLewis** [comment]
> Hi @AmosLewis Please let me know what you think about the above explanation. Happy to help!
This clears my confusion on the full_start_index and ds. Thanks a lot.

**Comment by sdasgup3** [comment]
I am glad to know that :)
In that case let me close this issue for now. Feel free to re-open if you have further questions around the same topic.

**Comment by AmosLewis** [comment]
https://gist.github.com/AmosLewis/197d7b0e512db98d44715f269ad30069

**Comment by AmosLewis** [comment]
@sdasgup3  I have one more questions. How do we set up the **update_window_dims**, **index_vector_dim** and **inserted_window_dims**?
Here are the examples I try to create but fail:

```
func.func @scatter_op_test() {
  %inputs = stablehlo.constant dense<[[0, 1, 2, 3]]> : tensor<1x4xi64>
  %scatter_indices = stablehlo.constant dense<[[0, 1], [0, 2], [0, 3]]> : tensor<3x2xi64>
  %updates = stablehlo.constant dense<[[4], [5], [6]]> : tensor<3x1xi64>
  %result = "stablehlo.scatter"(%inputs, %scatter_indices, %updates) ({
    ^bb0(%arg0: tensor<i64>):
      stablehlo.return %arg0 : tensor<i64>
  }) {
    scatter_dimension_numbers = #stablehlo.scatter<
      update_window_dims = [1],
      inserted_window_dims = [0],
      scatter_dims_to_operand_dims = [0, 1],
      index_vector_dim = 1>,
    indices_are_sorted = false,
    unique_indices = false
  } : (tensor<1x4xi64>, tensor<3x2xi64>, tensor<3x1xi64>) -> tensor<1x4xi64>
  check.expect_eq_const %result, dense<[[0, 4, 5, 6]]> : tensor<1x4xi64>
  func.return
}
```

This is how I use this value to derive the algorithm. [test_indexput_stablehlo_scatter_examples.txt](https://gist.github.com/AmosLewis/1ef4e7c549d5a3d3906e6b6f128d4f36#file-test_indexput_stablehlo_scatter_examples-txt)
Here is my torch-mlir patch which try to setup the args for scatter https://github.com/llvm/torch-mlir/pull/2343

**Comment by sdasgup3** [comment]
The above code has a few typos (In the code below I commented them out with proper labelling):
 - T0: '%updates' expects different type than prior uses:  'tensor<3x1xi64>' vs 'tensor<1x3xi64>'
 - T1: reduction region to have two arguments
 - T2: `%inputs` vs `%input`

Once the above are fixed, we have a error saying `expects bounds of the scatter dimensions of updates to be same as the bounds of the corresponding dimensions of scatter indices. For scatter dimension 0, updates bound is 1 , scatter_indices bound is 3.`, which comes from https://github.com/openxla/stablehlo/blob/main/docs/spec.md#constraints-70 (first bullet)

Once we fix that (using "Fix A" in the code snippet) we get the valid IR.
```
func.func @scatter_op_test() {
  %input = stablehlo.constant dense<[[0, 1, 2, 3]]> : tensor<1x4xi64>
  // %scatter_indices = stablehlo.constant dense<[[0, 1], [0, 2], [0, 3]]> : tensor<3x2xi64>
  // Fix A
  %scatter_indices = stablehlo.constant dense<[[0, 1]]> : tensor<1x2xi64>
  %updates = stablehlo.constant dense<[[4, 5, 6]]> : tensor<1x3xi64>
  // T2: %result = "stablehlo.scatter"(%inputs, %scatter_indices, %updates) ({
  %result = "stablehlo.scatter"(%input, %scatter_indices, %updates) ({
    // T1: ^bb0(%arg0: tensor<i64>):
    ^bb0(%arg0: tensor<i64>, %arg1: tensor<i64>):
      stablehlo.return %arg0 : tensor<i64>
  }) {
    scatter_dimension_numbers = #stablehlo.scatter<
      update_window_dims = [1],
      inserted_window_dims = [0],
      scatter_dims_to_operand_dims = [0, 1],
      index_vector_dim = 1>,
    indices_are_sorted = false,
    unique_indices = false
  // T0: } : (tensor<1x4xi64>, tensor<3x2xi64>, tensor<3x1xi64>) -> tensor<1x4xi64>
  } : (tensor<1x4xi64>, tensor<1x2xi64>, tensor<1x3xi64>) -> tensor<1x4xi64>
  // check.expect_eq_const %result, dense<[[0, 4, 5, 6]]> : tensor<1x4xi64>
  func.return
}
```

>> How do we set up the update_window_dims, index_vector_dim and inserted_window_dims based on the input?

The [inputs](https://github.com/openxla/stablehlo/blob/main/docs/spec.md#inputs-71)  to scatter op is bound by some [constraints](https://github.com/openxla/stablehlo/blob/main/docs/spec.md#constraints-70) that needs to be followed. 

>> For the index_vector_dim(1), some other patch always set it as [input rank (2)](https://github.com/llvm/torch-mlir/pull/2295/files#diff-37f576362dfffc48c6d013a2edd9357d53d2bb08345a7d8e7f7217cea90701c8R472:~:text=int64_t%20indexVecDim%20%3D%20inputType.getRank()%3B).

`index_vector_dim` is a property of the `scatter_indices` operand. With that I do not think the above will always be valid. 
From the [Inputs](https://github.com/openxla/stablehlo/blob/main/docs/spec.md#inputs-71) table, you will find that the `index_vector_dim` is constrainted using `C4, C11 and C14` and none of them are related to `inputs`. My suggestion would be to follow the constraints to choose values for constant inputs  (like `index_vector_dim`) and/or shapes for non-constant inputs (like `updates`, `scatter_indices` or `inputs`).

**Comment by AmosLewis** [comment]
@sdasgup3  What if the **%updates** shape is set to <3x2>? Would the following IR setting be correct?
And since you set the **T1**,  I have one more question **Q0**.

- Q0: Should it return the right arguments %arg1 instead of the left arguments %arg0?

```
func.func @scatter_op_test() {
  %input = stablehlo.constant dense<[[0, 1, 2, 3]]> : tensor<1x4xi64>
  %scatter_indices = stablehlo.constant dense<[[0, 1], [0, 2], [0, 3]]> : tensor<3x2xi64>
  //T3: %scatter_indices = stablehlo.constant dense<[[0, 1]]> : tensor<1x2xi64>
  %updates = stablehlo.constant dense<[[4], [5], [6]]> : tensor<3x1xi64>
  %result = "stablehlo.scatter"(%input, %scatter_indices, %updates) ({
    ^bb0(%arg0: tensor<i64>, %arg1: tensor<i64>):
      //Q0: Should it return %arg1 instead of %arg0???
      stablehlo.return %arg1 : tensor<i64>
  }) {
    scatter_dimension_numbers = #stablehlo.scatter<
      update_window_dims = [1],
      inserted_window_dims = [0],
      scatter_dims_to_operand_dims = [0, 1],
      index_vector_dim = 1>,
    indices_are_sorted = false,
    unique_indices = false
  // T4: } : (tensor<1x4xi64>, tensor<1x2xi64>, tensor<1x3xi64>) -> tensor<1x4xi64>
  } : (tensor<1x4xi64>, tensor<3x2xi64>, tensor<3x1xi64>) -> tensor<1x4xi64>
  // check.expect_eq_const %result, dense<[[0, 4, 5, 6]]> : tensor<1x4xi64>
  func.return
}
```

I got a similar IR created successfully by lowering torch.aten._index_put_impl into stablehlo.scatter:
`torch-mlir-opt --convert-torch-to-stablehlo test_indexput.mlir`
**Torch:**
```
func.func @torch.aten._index_put_impl(%input: !torch.vtensor<[1,4],si64>, %index: !torch.vtensor<[3],si64>, %fillValues: !torch.vtensor<[1,3],si64>) -> !torch.vtensor<[1,4],si64>{
  %false = torch.constant.bool false
  %none = torch.constant.none
  %indices = torch.prim.ListConstruct %none, %index : (!torch.none, !torch.vtensor<[3],si64>) -> !torch.list<optional<vtensor>>
  %out = torch.aten._index_put_impl %input, %indices, %fillValues, %false, %false : !torch.vtensor<[1,4],si64>, !torch.list<optional<vtensor>>, !torch.vtensor<[1,3],si64>, !torch.bool, !torch.bool -> !torch.vtensor<[1,4],si64>
  return %out : !torch.vtensor<[1,4],si64>
}
```
---> 
**Stablehlo:**
```
module {
  func.func @torch.aten._index_put_impl(%arg0: !torch.vtensor<[1,4],si64>, %arg1: !torch.vtensor<[3],si64>, %arg2: !torch.vtensor<[1,3],si64>) -> !torch.vtensor<[1,4],si64> {
    %0 = torch_c.to_builtin_tensor %arg0 : !torch.vtensor<[1,4],si64> -> tensor<1x4xi64>
    %1 = torch_c.to_builtin_tensor %arg2 : !torch.vtensor<[1,3],si64> -> tensor<1x3xi64>
    %false = torch.constant.bool false
    %none = torch.constant.none
    %2 = torch.prim.ListConstruct %none, %arg1 : (!torch.none, !torch.vtensor<[3],si64>) -> !torch.list<optional<vtensor>>
    %3 = torch_c.to_builtin_tensor %arg1 : !torch.vtensor<[3],si64> -> tensor<3xi64>
    %4 = stablehlo.constant dense<0> : tensor<3xi64>
    %5 = stablehlo.reshape %4 : (tensor<3xi64>) -> tensor<3x1xi64>
    %6 = stablehlo.reshape %3 : (tensor<3xi64>) -> tensor<3x1xi64>
    %7 = stablehlo.concatenate %5, %6, dim = 1 : (tensor<3x1xi64>, tensor<3x1xi64>) -> tensor<3x2xi64>
    %8 = stablehlo.reshape %1 : (tensor<1x3xi64>) -> tensor<3x1xi64>
    %9 = "stablehlo.scatter"(%0, %7, %8) ({
    ^bb0(%arg3: tensor<i64>, %arg4: tensor<i64>):
      stablehlo.return %arg4 : tensor<i64>
    }) {indices_are_sorted = false, scatter_dimension_numbers = #stablehlo.scatter<update_window_dims = [1], inserted_window_dims = [0], scatter_dims_to_operand_dims = [0, 1], index_vector_dim = 1>, unique_indices = false} : (tensor<1x4xi64>, tensor<3x2xi64>, tensor<3x1xi64>) -> tensor<1x4xi64>
    %10 = torch_c.from_builtin_tensor %9 : tensor<1x4xi64> -> !torch.vtensor<[1,4],si64>
    return %10 : !torch.vtensor<[1,4],si64>
  }
}
```

**Comment by sdasgup3** [comment]
>> What if the %updates shape is set to <3x2>? Would the following IR setting be correct?

Yes, as long as all the following constraints corresponding to `%updates` are met. In the torch-converted stablehlo program, that you  pasted above, satisfies all the constraints and hence the shape choice is valid. 

```
// All these constraints are collected from the spec
(C3) same(shape(updates...)).
(C4) shape(updates[0]) = combine(update_scatter_dim_sizes, update_window_dim_sizes) where:
(C5) 0 < size(inputs) = size(updates) = N.
(C6) element_type(updates...) = element_type(inputs...).
```

>> Q0: Should the reduction region return the right arguments %arg1 instead of the left arguments %arg0?

The reduction reduction is an arbitrary computation between an element from `update` tensor and `result` tensor provided the constraint https://github.com/openxla/stablehlo/blob/main/docs/spec.md#constraints-70 :: C15 is satisfied.
Having said that either choices are syntactically valid. The current choice makes sense based on the input torch program.

Hope this will help.
