### ISSUE TITLE
Decide what to do with interpretation of Not in HLO and Miscellaneous ops

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#1571]
We have frontend contract tickets that request moving Not in HLO ops (#3) and potentially Miscellaneous ops (#1570) out of StableHLO. All of these ops (except for FftOp) have passes implemented either on MHLO or HLO that decompose them into other StableHLO ops. I think this means that we could declare these decomposable ops as "kind of done" for now.

**Comment by burmako** [comment]
FWIW, here are the individual "implement interpretation for FooOp tickets": 
  * BatchNormGradOp, BatchNormInferenceOp, BatchNormTrainingOp: already implemented.
  * CholeskyOp: already implemented.
  * DotOp (Not in HLO): #1225.
  * EinsumOp (Not in HLO): #1226.
  * TorchIndexSelectOp (Not in HLO): #1227.
  * FftOp (Miscellaneous): #1126.
  * RngBitGeneratorOp (Miscellaneous): #1135.
  * RngOp (Miscellaneous): #1136.
  * TriangularSolveOp (Miscellaneous): #1138.

**Comment by GleasonK** [comment]
This blocks a few other P1 items in https://github.com/orgs/openxla/projects/7?pane=issue&itemId=29868960, may be worth considering bumping to P0 and making a formal plan for support of these ops and timelines.

**Comment by ghpvnist** [comment]
With #1573 merged, here is the updated list with all tickets created (with the exception of `trace`, which may be removed by #604)
  * BatchNormGradOp (Miscellaneous): #1121.
  * BatchNormInferenceOp (Miscellaneous): #963.
  * BatchNormTrainingOp (Miscellaneous): #1122.
  * BroadcastOp (Not in HLO): #1799.
  * CholeskyOp (Miscellaneous): #1123.
  * CreateTokenOp (Not in HLO): #1800.
  * CrossReplicaSumOp (Not in HLO): #1801.
  * DotOp (Not in HLO): #1225.
  * EinsumOp (Not in HLO): #1226.
  * FftOp (Miscellaneous): #1126.
  * RngBitGeneratorOp (Miscellaneous): #1135.
  * RngOp (Miscellaneous): #1136.
  * TorchIndexSelectOp (Not in HLO): #1227.
  * TraceOp (Not in HLO): N/A.
  * TriangularSolveOp (Miscellaneous): #1138.
  * UnaryEinsumOp (Not in HLO): #1802.

**Comment by ghpvnist** [comment]
Here are the remaining open issues:

Miscellaneous:
* FftOp: #1126
* RngBitGeneratorOp (Miscellaneous): #1135
* RngOp (Miscellaneous): #1138

Not in HLO:
* ComputeReshapeShapeOp: N/A - this op will be handled in #1668.
* CstrReshapableOp: N/A - this op will be handled in #1668.
* TraceOp: N/A - this op is not planned to be supported in the interpreter. See #604.

Any future work & removal of an op will be proposed in their respective tickets.
