### ISSUE TITLE
Figure out the story for per-axis quantization

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#1574]
What ops should support per-axis quantization? All of them? Only some of them? (E.g. dot_general). Need some clear criterion for this, rather than ad-hoc (per-op) rules. #1535 represents some ongoing work in that direction.

Also, how do we spec the semantics of per-axis quantization? Will we need to duplicate per-tensor and per-axis semantics for each supporting op? Or maybe there's some easy way out? In #1477, there's a sketch of the latter.

```
For simplicity, we only define individual operation semantics for per-tensor
quantized type. Semantics of per-axis type, if supported by the op, can be
derived as follows:

Given an operation specification with per-tensor quantized type, let the
semantics of the operation includes some application of the quantization
parameters `zero_point` and `scale` to a tensor element`e` at index = `[i0, ...,
id, ..., iR-1]`. The specification for the semantics of the same operation on
tensor element `e`, with per-axis quantized type with quantization dimension `d`
, would exactly be the same as the one with per-tensor type except that the
`zero_point` and `scale` will be replaced with their per-axis counterparts,
`zero_points[id]` and `scales[id]` resp.
```

**Comment by burmako** [comment]
Here's an example of how a more formal definition of quantized semantics for AddOp could look like:

```
For quantized types, `result[result_index] = result_element` where:
  * `float_lhs = (lhs[result_index] - zero_point(lhs, result_index)) * scale(lhs, result_index)`.
  * `float_rhs = (rhs[result_index] - zero_point(rhs, result_index)) * scale(rhs, result_index)`.
  * `float_result = float_lhs + float_rhs`.
  * `rounded_result = round_nearest_even(float_result / scale(result))`.
  * `result_element = clamp(storage_min(result), rounded_result + zero_point(result), storage_max(result))`.
```

It's more verbose, but it captures the semantics exactly, similarly to how we wrote the rest of the specification. I imagine that we may also find ways to compress it further by introducing some functions in #1556, for example:

```
For quantized types, `result[result_index] = result_element` where:
  * `float_lhs = uniform_dequantize(lhs[result_index], type(lhs), result_index)`
  * `float_rhs = uniform_dequantize(rhs[result_index], type(rhs), result_index)`
  * `float_result = float_lhs + float_rhs`.
  * `result_element = uniform_quantize(float_result, type(result), result_index)`.
```

**Comment by sdasgup3** [comment]
Relevant information: https://github.com/openxla/stablehlo/pull/1567#discussion_r1235085366

**Comment by sdasgup3** [comment]
Also we need to consider if ops will multiple operands like `add`, `max` should have quantization types with mixed quantization granularity (per-axis and per-tensor), similar to what we have for `dot_general` or `convolution`.

**Comment by sdasgup3** [comment]
After talking with various stakeholders, it seems that `add` (for bias addition to convolution result) might be  a candidate for per-axis quantization. A few things to explore while speccing its semantics:

1. The relation between the quantization dimension of `lhs`, `rhs`, and `result`.  
2. Is there a use case for `lhs`, `rhs` and `result` to have a mix of per-tensor and per-axis quantization scheme?

**Comment by dansuh17** [comment]
`dot_general` is also a strong candidate for allowing per-axis quantized tensors. Some actual use cases suggest that it should support for at least a mixed quantization scheme where it accepts per-tensor quantized lhs and per-axis quantized rhs and outputs a per-tensor quantized result. In my experience, this scheme is the most common that involves per-axis quantized tensors.

However, even if we scope down to supporting only this scheme, there are some complexities that weren't there for `convolution` because contracting dimensions involve reshapes (relevant: [Logan's previous comment](https://github.com/openxla/stablehlo/issues/1574#issuecomment-1601139759)).

Probably the support for per-axis quantized tensors for `reshape` and `transpose` should precede the spec for `dot_general`.

**Comment by sdasgup3** [comment]
Thanks @dansuh17 for the information!

>>  ... because contracting dimensions involve reshapes

Can you please elaborate on this? Some stablehlo code elaborating this would be very useful. 
I am curious to know if the use case involve any split or merge of input quantization_dimension which is non trivial to handle.

**Comment by loganchien** [comment]
According to the private discussion, I think the missing piece is the presentation for multi-axes per-axis quantized type.  Some model builders create multi-axes per-axis quantization by multiplying a 2D (or higher dimension) scales.  We don't have a representation for that.

If we want to emulate that with `ReshapeOp`, we will hit a constraint that disallows the breakdown of per-axis quantization.  The constraint was added because the current per-axis quantized type can only specify scales/zero_points pairs on one dimension and we want to keep `ReshapeOp` as a data movement op and keep it out of computation.

For example, here is a multi-axes per-axis quantization in primitive ops:

```
def dot_general_with_weight_only_quantization(lhs_fp, rhs_qui8, scales, lhs_contraction_dims, rhs_contraction_dims):
  rhs_fp = convert_to_float(rhs_qui8)
  dot = dot_general(lhs_fp, rhs_fp, lhs_contraction_dims, rhs_contraction_dims)
  dot_scale = dot * scales
  return dot_scale

input = ... : tesnor<B x Y x X x f32>
rhs_qui8 = ... : tensor<T x Y x X x i8>
scales = ... : tensor<T x 1 x X x f32>
result = dot_general_with_weight_only_quantization(input, rhs_qui8, scales, lhs_contraction_dims = [1, 2], rhs_contraction_dims = [1, 2])  // -> [B, T]
```

We wish to represent it with:

```
%lhs_fp = ... : tensor<... x f32>
%rhs_qui8 = "stablehlo.constant"() {value = ...} : tensor<T x Y x X x !quant.uniform<ui8:f32:{0,2}, {
  {scales[0][0][0], scales[0][0][1], ... scales[0][0][X-1]},
  {scales[1][0][0], scales[1][0][1], ... scales[1][0][X-1]},
  ...,
  {scales[T-1][0][0], scales[T-1][0][1], ... scales[T-1][0][X-1]}}>
%rhs_fp = "stablehlo.dequant_uniform"(%rhs_qui8)  # assume no hybrid for now
%res = "stablehlo.dot_general"(%lhs_fp, %rhs_fp)
```

But we don't have that representation, thus we try to emulate with `ReshapeOp` and `TransposeOp`.

For example, first we transpose RHS from T*Y*X to Y*T*X:

```
%lhs_fp = ... : tensor<... x f32>
%rhs_qui8 = "stablehlo.constant"() {value = ...} : tensor<T x Y x X x ...>
%rhs_qui8_trans = "stablehlo.transpose"(%rhs_qui8) : (tensor<T x Y x X x ...>) -> tensor<Y x T x X x ...>
%rhs_fp = "stablehlo.dequant_uniform"(%rhs_qui8_trans)  # assume no hybrid for now
%res = "stablehlo.dot_general"(%lhs_fp, %rhs_fp, , lhs_contraction_dims = [0, 2], rhs_contraction_dims = [0, 2])
```

But we face problem when we want to reshape `tensor<Y x T x X x ...>` into `tensor<Y x (T * X) x ...>` because `rhs_contraction_dims` specifies 0 and 2 but not 1.  If we merge them, we can't specify `rhs_contraction_dims`.


> Thanks @dansuh17 for the information!
> 
> > > ... because contracting dimensions involve reshapes
> 
> Can you please elaborate on this? Some stablehlo code elaborating this would be very useful. I am curious to know if the use case involve any split or merge of input quantization_dimension which is non trivial to handle.

**Comment by sdasgup3** [comment]
Thanks @loganchien for the explanation. This is very useful.  I agree with you that the current uniform quantized type with per-axis support is not cut for that. It would need  further exploration and , IMO, we can address it separately.

cc @dansuh17 @loganchien 

It seems we do have some separate use-cases to support (the usual) per-axis scheme for `transpose`, `reshape` and `dot_general` ops. Also, just to make sure that those use-cases for `reshape` does not need any split or merge of the quantization dimension. If we agree on that, how about we first address the specification of those?  Please let me know if this sounds like a plan?

**Comment by dansuh17** [comment]
sgtm! the constraints that I can think of from the top of my head are:

* Only the rhs of `dot_general` is allowed  to be a per-axis quantized tensor.
* Neither `contracting_dimension` nor the `batch_dimension` should be the quantization dimension.
* `reshape` can only "move" the quantization dimension (e.g. no splitting, merging, or both).
* The quantization dimension should be adjusted according to the permutation applied to `reshape` and `transpose`.

**Comment by loganchien** [comment]
As the initial step, let's add the following constraints to support per-axis quantization `dot_general` that can utilize the same hardware for `convolution`:

* `stablehlo.reshape`
  * C?: If the `operand` is a per-axis quantized tensor, the `result` must be a per-axis quantized tensor.
  * C?: `reduce(dim(operand, [0, 1, ..., quantization_dimension(operand) - 1]), init_values=1, body=multiply) = reduce(dim(result, [0, 1, ..., quantization_dimension(result) - 1]), init_values=1, body=multiply)`
  * C?: `dim(operand, quantization_dimension(operand)) = dim(result, quantization_dimension(result))`
  * C?: `reduce(dim(input_type, [quantization_dimension(operand) + 1, ..., rank(operand) - 1]), init_values=1, body=multiply) = reduce(dim(result, [quantization_dimension(result) + 1, ..., rank(result) - 1]), init_values=1, body=multiply)`
* `stablehlo.transpose`
  * C?: If the `operand` is a per-axis quantized tensor, the `result` must be a per-axis quantized tensor.
  * C?: `result.quantization_dimension == permutation[operand.quantization_dimension]`
* `stablehlo.dot_general`
  * `rhs` can be per-axis quantized tensor
  * `result` can be per-axis quantized tensor
  * C?: If `result` is per-axis quantized tensor, `quantization_dimension(result) == rank(result) - 1`
  * C?: `quantization_dimension(rhs)` not in `rhs_batch_dimensions`
  * C?: `quantization_dimension(rhs)` not in `rhs_contraction_dimensions`
    * Rationale: `quantization_dimension(rhs)` must not be in `rhs_contraction_dimensions` because the almost-integer kernel performs the multiply-accumulation in integers and then rescale the accumulated value right before returning the output value. If the `quantization_dimension(rhs)` is contracted, the kernel must rescale integers (or dequantize integers) while doing multiply-accumulation and that contradicts to the purpose of per-axis quantization.
* `stablehlo.uniform_quantize`
  * `result` can be per-axis quantized tensor
* `stablehlo.uniform_dequantize`
  * `input` can be per-axis quantized tensor

We will also need PR #1702.

**Comment by doyeonkim0** [comment]
> `stablehlo.uniform_quantize`
> * `result` can be per-axis quantized tensor

Won't we need per-axis quantized `input` for requantization?

**Comment by doyeonkim0** [comment]
> 



> After talking with various stakeholders, it seems that `add` (for bias addition to convolution result) might be a candidate for per-axis quantization. A few things to explore while speccing its semantics:
> 
> 1. The relation between the quantization dimension of `lhs`, `rhs`, and `result`.
> 2. Is there a use case for `lhs`, `rhs` and `result` to have a mix of per-tensor and per-axis quantization scheme?
> 
> relevant discussion: [#1446 (comment)](https://github.com/openxla/stablehlo/pull/1446#discussion_r1278896836)

In the use case for bias addition in convolution quantization, lhs, rhs and result are all per-axis quantized, have same quantization axes, quantization parameters and shapes.

**Comment by loganchien** [comment]
> > `stablehlo.uniform_quantize`
> > 
> > * `result` can be per-axis quantized tensor
> 
> Won't we need per-axis quantized `input` for requantization?

Thank you for point this out.  Yes, `stablehlo.uniform_quantization` should support per-axis quantized tensor as its `input` as well.

**Comment by doyeonkim0** [comment]
> Re:
> 
> ```
> stablehlo.uniform_quantize: result can be per-axis quantized tensor
> stablehlo.uniform_dequantize: input can be per-axis quantized tensor
> ```
> 
> The above is supported in the current spec.
> 
> > > In the use case for bias addition in convolution quantization, lhs, rhs and result are all per-axis quantized, have same quantization axes, quantization parameters and shapes.
> 
> From [#1446 (comment)](https://github.com/openxla/stablehlo/pull/1446#discussion_r1278896836) it seems that we might have a use-case when the `lhs` can be per-tensor. cc/ @dansuh17
> 
> For operation like add, whose spec are defined in terms of dequant-op-quant, allow us with the flexibility to support any mix of per-tensor/per-axis among its operands and result and the implementations should be free to tune into a specific subset of behaviors (e.g. all operands / result types to be per-axis or per-tensor). How about we allow the per-axis / per-tensor mix for the add op, which include 8 combination for `lhs`, `rhs` and `result`. This could save us from future iterations on the spec as it seems they are highly possible to occur in some future use cases (if not now).

After looking at the spec again, current stablehlo.uniform_quantize/dequantize already supports all use cases we have been discussing.

Also, allowing all combinations for lhs, rhs and result in the spec sounds good to me.

**Comment by sdasgup3** [comment]
Relevance of per-axis support for dot-general op: 
 https://github.com/openxla/stablehlo/issues/1615
