### ISSUE TITLE
Adopt properties for StableHLO dialects

### ISSUE THREAD

**Issue by joker-eph** [openxla/stablehlo#1584]
### Request description

Upstream has now an option to assist in the migration to properties. You probably wanna to try to switch before upstream changes the default and deprecate the current settings.

In general the switch is fairly trivial, here is an example of how it was done in OpenAI Triton:

- https://github.com/openai/triton/pull/1684
- https://github.com/openai/triton/pull/1696

Some extra cleanup that is worthwhile is to replace all uses of getDictionaryAttr to more targeted APIs, this one is now quite costly.

**Comment by burmako** [comment]
"Some extra cleanup that is worthwhile is to replace all uses of getDictionaryAttr to more targeted APIs, this one is now quite costly". Yeah, this is exactly why we haven't yet upgraded. StableHLO <=> MHLO and StableHLO <=> VHLO is based on getAttrs ([example](https://github.com/tensorflow/mlir-hlo/blob/78fac553dbcd2282cfca8a5fb978bc4a76f5a74d/mhlo/transforms/stablehlo_legalize_to_hlo/stablehlo_legalize_to_hlo.cc#L244-L253)), and we haven't yet had the time to think what to do instead.

"You probably wanna to try to switch before upstream changes the default and deprecate the current settings". Thank you for thinking about us! What timeline do you expect for deprecating and stopping to support old-style attributes?

**Comment by joker-eph** [comment]
I don't have a timeline right now, the first milestone will be switching the default, hopefully before the end of the month. Then it'll likely take a few months at least to hammer down everything.

**Comment by GleasonK** [comment]
Nice! I'll take a look at this in the near future. Will post in the discord if I hit any issues along the way!

**Comment by GleasonK** [comment]
Adding compatibility label since VHLO will need to be migrated as well
