### ISSUE TITLE
Keep track of completeness of the implementation

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#16]
It would be good to have an easy way to see how far along we are with supporting various aspects of the implementation - prettyprinting, verification, shape inference, interpreter, etc. Perhaps we could have a Markdown document that tracks this status? (#5 and #6 look like related work for this ticket).

**Comment by bhack** [comment]
Do we want to track what discussed at https://github.com/openxla/stablehlo/pull/331#issuecomment-1279230451 here?

But I don't know if you want to reopen this specific ticket.

**Comment by burmako** [comment]
@bhack Thank you for following up! I've opened #355 to track this work. Not sure if I'll have cycles for this in the very near future, but I agree that it'll be good to not forget about this!

**Comment by bhack** [comment]
Ok thanks
