### ISSUE TITLE
Should dot_general support per-axis quantization scheme? 

### ISSUE THREAD

**Issue by sdasgup3** [openxla/stablehlo#1615]
From the 
- TFLite [spec](https://www.tensorflow.org/lite/performance/quantization_spec#int8_quantized_operator_specifications), and
- https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/reference/fully_connected.h

It seems like TFLite fully_connected op does not support per-axis. 

The per-axis scheme is [added](https://github.com/openxla/stablehlo/blob/main/docs/spec.md#dot_general) to StableHLO `dot_general` op mainly because of the fact that `dot_general` is used in the [specification](https://github.com/openxla/stablehlo/blob/main/docs/spec.md#convolution) of convolution op. IMO, that should not be the only reason to include per-axis scheme to dot_general. 

The ticket is about re-visiting the spec of `dot_general` and explore use-case for it to support per-axis quantization scheme.

**Comment by rewu93** [comment]
Currently TFLite does not support per-axis quantized FC. However, we do see the rising demands for it due to the dramatic size increase of recent models. We may add it in the future.

**Comment by jingpu** [comment]
+1 per-axis quantization FC seems useful for LLM

**Comment by sdasgup3** [comment]
This issue is tracked as part of https://github.com/openxla/stablehlo/issues/1574. Closing this for now. 

For record: The current state of dot-general is that it support per-tensor quantized type which is implemented via https://github.com/openxla/stablehlo/pull/1700.
