### ISSUE TITLE
Finalize the spec for quantized AllReduceOp, BatchNormTrainingOp, BatchNormGradOp and ReduceScatterOp

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#1666]
These ops all use reduction whose quantized representation is currently being discussed in #1538. Following the resolution of this discussion, let's apply its outcome to these ops as well.

**Comment by abhigunj** [comment]
for the all four ops spec is updated at  https://github.com/openxla/stablehlo/pull/1796
