### ISSUE TITLE
Decide on quantizing RNG operations

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#1667]
In #1647, we decided to factor out this into a separate discussion topic. Let's get to the bottom of this.

**Comment by abhigunj** [comment]
https://github.com/openxla/stablehlo/pull/1647#issuecomment-1607857449 proposed to exclude `rng`  and `rng_bit_generator ` from quantization speccing.

`rng` op :  from conversations with many stakeholders, this op has come up as effectively deprecated, so in the future we are planning to explore removing it (https://github.com/openxla/stablehlo/issues/597).

`rng_bit_generator`  :  This op generates a randomized output tensor based on a rng_algorithm algorithm (DEFAULT, THREE_FRY, and PHILOX). It is not clear how there algorithm should handle generating quantized output.  proposal here is to skip quantization of this op unless we have a use case for it

we propose to close this ticket for now, and will be open to revisit on need basis.
