### ISSUE TITLE
Revisit the handling of complex constants: `mlir::ArrayAttr` vs `complex::NumberAttr`.

### ISSUE THREAD

**Issue by sdasgup3** [openxla/stablehlo#175]
### Request description

This issue comes up from @burmako [comment](https://github.com/openxla/stablehlo/commit/4e64ed15a8db41ae990bed609a48c88cd6d2e055#r84620214).

Instead of handling complex constants as `mlir::ArrayAttr`, we can instead use  [recently](https://github.com/llvm/llvm-project/commit/5caa941f683270c3e5078ec46f208212b565c505) introduced `complex::NumberAttr`.

**Comment by burmako** [comment]
This ticket is going to become moot with the recent refactoring of `Element` to not use attributes at all: https://github.com/openxla/stablehlo/pull/101.
