### ISSUE TITLE
Provide standardized interface for calling reference interpreter

### ISSUE THREAD

**Issue by penagos** [openxla/stablehlo#1780]
### Request description

Today, it isn't practical to call the StableHLO reference interpreter. Invoking the interpreter requires going through the MLIR translate infrastructure (i.e. via `interpretRegistration` in `StablehloTranslateMain.cpp`), and does not currently support specifying user inputs into a model or doing any meaningful post processing on the model outputs short of printing them to screen. This makes it difficult to run StableHLO MLIR models.

It would be great to provide a standardized API to call into the StableHLO reference interpreter, in which clients could specify the following:

1. The StableHLO MLIR (or `ModuleOp`) to be executed
2. The model inputs, as `InterpreterValue` instances
3. An optional interpretation fallback callback (which defaults to the existing `interpreterFallback` in `StablehloTranslateMain.cpp`)

Akin to `eval`, the interface could return a `SmallVector<InterpreterValue>` of result tensors. While I think the `eval` method might be able to be repurposed for this feature, I think lower level abstractions (such as `Region`s, `Scope`s and `Process`es should not be something which are required & exposed to downstream users).

**Comment by GleasonK** [comment]
This has been completed in https://github.com/openxla/stablehlo/pull/1784 and a few followup PRs
