### ISSUE TITLE
The parameters of ScatterOp, especially ScatterDimensionNumbers, are really confusing. Any more concret examples for this op?

### ISSUE THREAD

**Issue by eedalong** [openxla/stablehlo#1859]

**Comment by eedalong** [comment]
<img width="1230" alt="截屏2023-11-24 17 47 13" src="https://github.com/openxla/stablehlo/assets/39682259/c305bfc0-1691-4e7b-897d-b131e134a829">
Anybody know how do we get this update_index?

**Comment by sdasgup3** [comment]
Let me get back to you to this asap.

**Comment by eedalong** [comment]
Great, this is really clear. Thx!

**Comment by sdasgup3** [comment]
Glad that it helped. Closing the issue for now. Feel free to re-open.
