### ISSUE TITLE
Interpreter for AndOp, OrOp, XorOp, and NotOp

### ISSUE THREAD

**Issue by sdasgup3** [openxla/stablehlo#205]
### Request description

We already have the specification for those.

**Comment by burmako** [comment]
In October, we'll be focusing on control flow, data movement and reduction ops to frontload more difficult ops as we're working towards StableHLO v1.0. Unassigning this ticket for now.

**Comment by burmako** [comment]
Implemented in https://github.com/openxla/stablehlo/pull/286.
