### ISSUE TITLE
Add spec and implement interpreter for the PowOp

### ISSUE THREAD

**Issue by sdasgup3** [openxla/stablehlo#206]
### Request description

Spec and interpreter for `stablehlo.power`

**Comment by burmako** [comment]
In October, we'll be focusing on control flow, data movement and reduction ops to frontload more difficult ops as we're working towards StableHLO v1.0. Unassigning this ticket for now.

**Comment by burmako** [comment]
Spec for PowOp has been implemented in 2022, interpreter ticket the tracks this work now lives in #981.
