### ISSUE TITLE
Remove unranked type verifications in type inference and elsewhere

### ISSUE THREAD

**Issue by ghpvnist** [openxla/stablehlo#2065]
There's ongoing work (e.g. #2049) on disallowing unranked types for dynamism, and while working on shape refinement, I noticed that we still have checks to assert ranked types.

There are several instances of shape inference code that checks that the tensor types are ranked types (e.g. [here](https://github.com/openxla/stablehlo/blob/c2fccec9f02daa2d709001ed5f37924d2526676f/stablehlo/dialect/TypeInference.cpp#L1893-L1898)). Since we now disallow unranked types in the ODS, we can probably remove such verifications (likely deadcode).

**Comment by mlevesquedion** [comment]
Thanks! This is on my list of tasks for implementing the RFC: https://github.com/openxla/stablehlo/issues/1991#issue-2119623349. I linked to this new issue there.

**Comment by mlevesquedion** [comment]
With https://github.com/openxla/stablehlo/pull/2119, https://github.com/openxla/stablehlo/issues/2138, https://github.com/openxla/stablehlo/issues/2139, https://github.com/openxla/stablehlo/pull/2183 and https://github.com/openxla/stablehlo/pull/2217, I will consider this done.
