### ISSUE TITLE
Add spec and implement the interpreter for  SelectOp

### ISSUE THREAD

**Issue by sdasgup3** [openxla/stablehlo#208]
### Request description

Spec and interpreter for `stablehlo.select`

**Comment by burmako** [comment]
In October, we'll be focusing on control flow, data movement and reduction ops to frontload more difficult ops as we're working towards StableHLO v1.0. Unassigning this ticket for now.

**Comment by burmako** [comment]
Spec for SelectOp has been implemented in 2022, interpreter ticket the tracks this work now lives in #989.
