### ISSUE TITLE
Integration with JAX

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#217]
Now that StableHLO is ready to supersede MHLO as a compiler interface, we'll start integrating it with JAX. One nuance here is that a significant part of JAX/MHLO integration is happening in Python (e.g. see [lax.py](https://github.com/google/jax/blob/500f8b7f9c6bc6e7b273f2437b6481f48d3a57c0/jax/_src/lax/lax.py)), but we already have StableHLO Python bindings working, and they [are already in JAX dependencies](https://github.com/google/jax/blob/500f8b7f9c6bc6e7b273f2437b6481f48d3a57c0/jaxlib/mlir/BUILD.bazel#L146-L158).

**Comment by burmako** [comment]
It is now possible to obtain StableHLO representation of `@jax.jit` functions through the official JAX API introduced in https://github.com/google/jax/commit/55996328f25af7bd3b322b71bb5759ca45b63571. Further steps for integration with JAX are:
  1. Use `.stablehlo()` as the interface through which JAX talks to compilers (currently, this is MHLO).
  2. Use StableHLO as the native IR produces by JAX (currently, this is MHLO).

**Comment by bhack** [comment]
I understand that this question it is a little bit on the framework side but with all these Ops spec in progress does it has a fail fast approach?

**Comment by burmako** [comment]
What do you mean by "a fail fast approach"?

**Comment by bhack** [comment]
I have 3 ops and only 1 is already covered by StableHLO it is going to fail on the 1st unsupported (fail fast) or I have a full overview of the missing ops?

**Comment by burmako** [comment]
All JAX primitives are going to be covered by StableHLO one way or another - either directly via corresponding StableHLO ops or via `stablehlo.custom_call`.

**Comment by bhack** [comment]
Ok so something like:
```python
import jax.numpy as jnp
import jax
def e(x):
  return jnp.sin(jnp.cos(x)) + jnp.sign(x)
stablehlo = str(jax.jit(e).lower(2.).compiler_ir(dialect="stablehlo"))
print(stablehlo)
```

```mlir
module @jit_e {
  func.func public @main(%arg0: tensor<f32>) -> tensor<f32> {
    %0 = stablehlo.cosine %arg0 : tensor<f32>
    %1 = stablehlo.sine %0 : tensor<f32>
    %2 = call @sign(%arg0) : (tensor<f32>) -> tensor<f32>
    %3 = stablehlo.add %1, %2 : tensor<f32>
    return %3 : tensor<f32>
  }
  func.func private @sign(%arg0: tensor<f32>) -> tensor<f32> {
    %0 = stablehlo.sign %arg0 : tensor<f32>
    return %0 : tensor<f32>
  }
}
```

Where the Sign Op is under review in StableHLO at https://github.com/openxla/stablehlo/pull/494

**Comment by bhack** [comment]
Or probably not as we have already the op in the dialect before the spec is approved:

https://github.com/openxla/stablehlo/blob/efbd99463f386acc40887c59140e71a5419481d8/stablehlo/dialect/StablehloOps.td#L572

**Comment by burmako** [comment]
That's right. StableHLO has been forked from MHLO to include all ops that are used from JAX, PyTorch and TF, so we're pretty much covered at the moment.

When in the future XLA introduces some new public functionality to MHLO, this functionality will initially be supported in StableHLO via `custom_call`. Then, through the StableHLO RFC process, it will be proposed for inclusion in StableHLO, and depending on the outcome of the process might end up supported directly through native StableHLO ops. But regardless of how this goes, it will be covered by StableHLO either way.

**Comment by bhack** [comment]
> That's right. StableHLO has been forked from MHLO to include all ops that are used from JAX, PyTorch and TF, so we're pretty much covered at the moment.

Thank you for the clarification, it was really not clear that in progress specs, reference impl, etc in the repo are a sort of "reverse engineering" of the dialect in this phase.

**Comment by burmako** [comment]
We have just landed the migration of JAX from MHLO to StableHLO: https://github.com/google/jax/commit/a1480c454e69a2631dbd51cb2f4fccc2752c18a0. 

The linked commit goes into details of what exactly changed, but in a nutshell instead of `mhlo.foo` ops, JAX will now produce `stablehlo.foo` ops with several possibilities to transform this to MHLO if needed. Also, MHLO ops are still available to be used from JAX to provide access to cutting-edge XLA functionality (since such functionality, by definition, may take some time to appear in StableHLO).
