### ISSUE TITLE
Request CAPI implementation between python binding and c++ on `eval_module`, `serialize_portable_artifact` and `deserialize_portable_artifact`

### ISSUE THREAD

**Issue by qingyunqu** [openxla/stablehlo#2170]
### What happened?

When I try to integrate stablehlo refbackend in https://github.com/llvm/torch-mlir, I find that stablehlo's python api `eval_module()` doesn't call detailed implementation through CAPI which caused failure.
Calling through CAPI is standard method that calling from python binding to c++ in MLIR. I think it's necessary to  refactor stablehlo's python binding implementation.

**Comment by qingyunqu** [comment]
@GleasonK Could you please review this issue? Or there is anyone else who is familiar with python binding?

**Comment by GleasonK** [comment]
What's the best way to repro? Do you have a branch/patch in torch-mlir? That and a build command would be helpful

**Comment by qingyunqu** [comment]
> What's the best way to repro? Do you have a branch/patch in torch-mlir? That and a build command would be helpful

Thanks for response. I will give an example in torch-mlir as soon as possible.

**Comment by qingyunqu** [comment]
I find that Interpter works in torch-mlir correctly. I will close this issue and open another issue.
