### ISSUE TITLE
Integration with PyTorch/XLA

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#218]
In the last few weeks, we've been having active conversations with @shauheen and @miladm, and we're working on a plan for adoption of StableHLO in PyTorch/XLA. Will keep this ticket posted about our progress!

**Comment by miladm** [comment]
Thanks for creating this ticket @burmako. I am working on a RFC for integrating StableHLO in PyTorch/XLA. 

CC @shauheen, @JackCaoG

**Comment by GleasonK** [comment]
We now have a more clear plan of how TorchXLA and StableHLO interact. And we now have several APIs in TorchXLA to export StableHLO: [TorchXLA > stablehlo.md](https://github.com/pytorch/xla/blob/master/docs/stablehlo.md).

Given this, I am closing this ticket. If additional support is needed, this should be done using finer grained tickets.
