### ISSUE TITLE
Integration with Torch-MLIR

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#219]
We've been chatting about StableHLO in the #torch-mlir channel on LLVM's discord, and @silvasean recommended to migrate Torch-MLIR from MHLO to StableHLO. Sean has kindly offered to provide pointers, and I'm planning to take him up on his offer in the near future! 🚀

**Comment by burmako** [comment]
Implemented in https://github.com/llvm/torch-mlir/pull/1840. @ashay Thank you so much for your contribution!!

**Comment by ashay** [comment]
Thanks, it was easier than I thought, because of the near 1:1 correspondence between MHLO and StableHlo operators!
