### ISSUE TITLE
Request Interpreter to support dynamic shape basicly

### ISSUE THREAD

**Issue by qingyunqu** [openxla/stablehlo#2202]
### Request description

I find that Interperter doesn't support dynamic shape currently, like:
```python
from stablehlo import ir
from stablehlo._mlir_libs._stablehlo import register_dialect, eval_module

module_str = """
func.func @main(%arg0: tensor<?xf32>, %arg1: tensor<2xi64>) -> tensor<?x?xf32> {
    %0 = stablehlo.dynamic_reshape %arg0, %arg1 : (tensor<?xf32>, tensor<2xi64>) -> tensor<?x?xf32>
    return %0 : tensor<?x?xf32>
}
"""

context = ir.Context()
register_dialect(context)
with context:
    module = ir.Module.parse(module_str)
    print(module.operation.get_asm())

with context:
    a = ir.DenseFPElementsAttr(ir.Attribute.parse("dense<[0.0, 1.0, 2.0, 3.0]> : tensor<4xf32>"))
    b = ir.DenseIntElementsAttr(ir.Attribute.parse("dense<[2, 2]> : tensor<2xi64>"))
    print(a)

c = eval_module(module, [a, b])
print(c)
```

Is there any timeline to accomplish this?

**Comment by qingyunqu** [comment]
We'd be happy to help expedite this.

**Comment by sdasgup3** [comment]
Hi @qingyunqu 
My plan of implementation here would be to use augment the interpreter with shape refinement of dynamic arguments of the program with static shapes before interpreting the program. That should be good to address this request: The dynamic_shapes should all be folded to their static counterpart after [StablehloCanonicalizeDynamism](https://github.com/openxla/stablehlo/blob/main/stablehlo/transforms/StablehloCanonicalizeDynamism.cpp) pass. 

On a separate note:
Currently there is no support for interpreting dynamic_* stablehlo ops as such, so feel free to add that support.
