### ISSUE TITLE
Bug report on all_to_all implementation in stablehlo interpreter

### ISSUE THREAD

**Issue by Hatsunespica** [openxla/stablehlo#2433]
### What happened?

Let's consider the `all_to_all` operation described in spec https://github.com/openxla/stablehlo/blob/main/docs/spec.md#all_to_all 
and use the same example in the diagram but with a different `replica_group=[[1,0]]`

In other words, we have two tensors:
```
    %inputs0 = stablehlo.constant dense<[[1, 2, 3, 4],
                                         [5, 6, 7, 8]]> : tensor<2x4xi64>
    %inputs1 = stablehlo.constant dense<[[9, 10, 11, 12],
                                         [13, 14, 15, 16]]> : tensor<2x4xi64>
 
```
and want to perform an `all_to_all` operation with following attributes:
```
      split_dimension = 1 : i64,
      concat_dimension = 0 : i64,
      split_count = 2 : i64,
      replica_groups = dense<[[1, 0]]> : tensor<1x2xi64>

```

Similarly, we can derive `process_group=[[(1,0), (0,0)]]`, and let's do steps mentioned in the spec:

```
split_parts...@sender = split(operands...@sender, split_count, split_dimension) for all sender in process_group.
scattered_parts...@receiver = [split_parts...@sender[receiver_index] for sender in process_group] where receiver_index = process_group.index(receiver).
results...@process = concatenate(scattered_parts...@process, concat_dimension).
```

```
#process_group=[[(1,0), (0,0)]]
#split_parts:

split_parts@input0=[ [[1,2],[5,6]], [[3,4], [7,8]] ]
split_parts@input1=[ [[9,10], [13,14]], [[11,12], [15,16]] ]

#scattered_parts:
scattered_parts@0 = [split_parts@sender[1] for sender in process_group]
 |
 V
scattered_parts@0=[ [[11, 12], [15, 16]], [[3, 4], [7, 8]] ]

scattered_parts@1 = [split_parts@sender[0] for sender in process_group]
 |
 V
scattered_parts@1= [ [[9, 10], [13, 14]], [[1,2], [5,6]] ] 

#results
result@0=  [[11, 12], [15, 16], [3, 4], [7, 8]]
result@1= [[9,10], [13, 14], [1, 2], [5, 6]]
```

However, when it comes to our interpreter, it becomes:
<img width="171" alt="image" src="https://github.com/user-attachments/assets/0774dc15-8d2f-424c-a89e-b74d5d7e52c3">

Reason guess : In `scatter` or `concat` step, the interpreter didn't follow the order `for sender in process_group`, but used the order `0, 1, ..., n`. `all_gather` implement it correctly so the concat order does change with `replica_group`

### Steps to reproduce your issue

1. Create a test file called `all_to_all.mlir`:
```
module @cross_replica {
  func.func @all_to_all(%operand : tensor<2x4xi64>) -> tensor<4x2xi64> {
    %result = "stablehlo.all_to_all"(%operand) {
      split_dimension = 1 : i64,
      concat_dimension = 0 : i64,
      split_count = 2 : i64,
      replica_groups = dense<[[1, 0]]> : tensor<1x2xi64>
    } : (tensor<2x4xi64>) -> tensor<4x2xi64>
    return %result : tensor<4x2xi64>
  }
  func.func @main() -> (tensor<4x2xi64>, tensor<4x2xi64>) {
    %inputs0 = stablehlo.constant dense<[[1, 2, 3, 4],
                                         [5, 6, 7, 8]]> : tensor<2x4xi64>
    %inputs1 = stablehlo.constant dense<[[9, 10, 11, 12],
                                         [13, 14, 15, 16]]> : tensor<2x4xi64>
    %results:2 = "interpreter.run_parallel"(%inputs0, %inputs1) {
      programs=[[@all_to_all], [@all_to_all]]
    } : (tensor<2x4xi64>, tensor<2x4xi64>) -> (tensor<4x2xi64>, tensor<4x2xi64>)
    func.return %results#0, %results#1 : tensor<4x2xi64>, tensor<4x2xi64>
  }
}

```
2. Run: `./stablehlo-translate --interpret all_to_all.mlir`. The output has a mismatch with the spec.

### Version information

My current HEAD:

commit aea942ea85b6769b057372ee798f1ad06b18e013 (HEAD -> main, origin/main, origin/HEAD)
Author: Pearu Peterson <pearu.peterson@gmail.com>
Date:   Thu Jul 4 01:46:52 2024 +0300

    Improve accuracy of complex and real acosh (#2411)
    
    - Improve the accuracy of complex acosh as follows (complex64):
      ```
                             current main  -> this PR
      ULP difference == 0 count is 141180  -> 839342
      ULP difference == 1 count is 10145   -> 162239
      ULP difference == 2 count is 1929    -> 420
      ULP difference == 3 count is 826     -> 0
      ULP difference >= 4 count is 847921  -> 0
      ```
    
    - Improve the accuracy of real acosh as follows (float32):
      ```
                               current main  -> this PR
      ULP difference == 0 count is 966912    -> 993686
      ULP difference == 1 count is 33008     -> 6303
      ULP difference == 2 count is 49        -> 12

**Comment by abhigunj** [comment]
@Hatsunespica  thanks for creating this ticket with all the necessary details, logs. The issue is now fixed via https://github.com/openxla/stablehlo/pull/2457. Let us know if you see any further issues.
