### ISSUE TITLE
Request more support of dynamic shape in Interpreter

### ISSUE THREAD

**Issue by qingyunqu** [openxla/stablehlo#2435]
### Request description

Stablehlo Interpreter failed on:
```
module attributes {torch.debug_module_name = "ArgmaxKeepdimModule"} {
  func.func @forward(%arg0: tensor<?x?xf32>, %arg1: tensor<?x?xf32>) -> tensor<?x?xf32> {
    %cst0 = arith.constant 0 : index
    %cst1 = arith.constant 1 : index
    %dim0 = tensor.dim %arg0, %cst0 : tensor<?x?xf32>
    %dim1 = tensor.dim %arg0, %cst1 : tensor<?x?xf32>
    %0 = tensor.from_elements %dim0, %dim1 : tensor<2xindex>
    %1 = "stablehlo.dynamic_broadcast_in_dim"(%arg1, %0) {broadcast_dimensions = array<i64: 0, 1>} : (tensor<?x?xf32>, tensor<2xindex>) -> tensor<?x?xf32>
    %2 = stablehlo.add %arg0, %1 : tensor<?x?xf32>
    return %2 : tensor<?x?xf32>
  }
}
```

I think there are many variants of dynamic shape, like usage of `shape.shape_of`, `shape.num_elements` and so on.

**Comment by sdasgup3** [comment]
Can you provide more details on the failures you are interested in? The stablehlo interpreter cannot evaluate operations from `arith` or `tensor` dialect as is. Also the interpreter might complain if the `dynamic_boradcast_in_dim` has dynamic result types ([cs])(https://github.com/openxla/stablehlo/blob/283f41ce1f2a623e99b73131debfcc76a5b7da16/stablehlo/reference/Ops.cpp#L331). This is a current limitation but can be mitigated. 

 However, the following stablehlo program, which is equivalent to the one you have, 

```python  
  module_str = """
module attributes {torch.debug_module_name = "ArgmaxKeepdimModule"} {
  func.func @forward(%arg0: tensor<?x?xf32>, %arg1: tensor<?x?xf32>) -> tensor<?x?xf32> {
  %dim0 = "stablehlo.get_dimension_size"(%arg0) <{dimension = 0 : i64}> : (tensor<?x?xf32>) -> tensor<i32>
  %dim1 = "stablehlo.get_dimension_size"(%arg0) <{dimension = 1 : i64}> : (tensor<?x?xf32>) -> tensor<i32>
  %rdim0 = "stablehlo.reshape"(%dim0) : (tensor<i32>) -> tensor<1xi32>
  %rdim1 = "stablehlo.reshape"(%dim1) : (tensor<i32>) -> tensor<1xi32>
    %0 = "stablehlo.concatenate"(%rdim0, %rdim1) { dimension = 0 : i64 } : (tensor<1xi32>, tensor<1xi32>) -> tensor<2xi32>
    %1 = "stablehlo.dynamic_broadcast_in_dim"(%arg1, %0) {broadcast_dimensions = array<i64: 0, 1>} : (tensor<?x?xf32>, tensor<2xi32>) -> tensor<?x?xf32>
    %2 = stablehlo.add %arg0, %1 : tensor<?x?xf32>
    return %2 : tensor<?x?xf32>
  }
}

"""

with ir.Context() as context:
    register_dialect(context)
    module = ir.Module.parse(module_str)
    input1 = ir.DenseElementsAttr.get(np.random.random(size=(2, 2)).astype(np.float32))
    input2 = ir.DenseElementsAttr.get(np.random.random(size=(1, 1)).astype(np.float32))
    mlir_args = [input1, input2]
    rets = eval_module(module, mlir_args)
    print(rets)
```



might not face that particular issue as the [pass pipeline](https://github.com/openxla/stablehlo/blob/283f41ce1f2a623e99b73131debfcc76a5b7da16/stablehlo/transforms/PassPipelines.cpp#L32) which is baked into the `eval_module`, will reduce it into 
```
 func.func @forward(%arg0: tensor<2x2xf32>, %arg1: tensor<1x1xf32>) -> tensor<2x2xf32> {
    %0 = stablehlo.broadcast_in_dim %arg1, dims = [0, 1] : (tensor<1x1xf32>) -> tensor<2x2xf32>
    %1 = stablehlo.add %arg0, %0 : tensor<2x2xf32>
    return %1 : tensor<2x2xf32>
  }

```

**Comment by qingyunqu** [comment]
> Can you provide more details on the failures you are interested in? The stablehlo interpreter cannot evaluate operations from `arith` or `tensor` dialect as is. Also the interpreter might complain if the `dynamic_boradcast_in_dim` has dynamic result types ([cs])(
> 
> https://github.com/openxla/stablehlo/blob/283f41ce1f2a623e99b73131debfcc76a5b7da16/stablehlo/reference/Ops.cpp#L331
> 
> ). This is a current limitation but can be mitigated.
> However, the following stablehlo program, which is equivalent to the one you have,
> 
> ```python
>   module_str = """
> module attributes {torch.debug_module_name = "ArgmaxKeepdimModule"} {
>   func.func @forward(%arg0: tensor<?x?xf32>, %arg1: tensor<?x?xf32>) -> tensor<?x?xf32> {
>   %dim0 = "stablehlo.get_dimension_size"(%arg0) <{dimension = 0 : i64}> : (tensor<?x?xf32>) -> tensor<i32>
>   %dim1 = "stablehlo.get_dimension_size"(%arg0) <{dimension = 1 : i64}> : (tensor<?x?xf32>) -> tensor<i32>
>   %rdim0 = "stablehlo.reshape"(%dim0) : (tensor<i32>) -> tensor<1xi32>
>   %rdim1 = "stablehlo.reshape"(%dim1) : (tensor<i32>) -> tensor<1xi32>
>     %0 = "stablehlo.concatenate"(%rdim0, %rdim1) { dimension = 0 : i64 } : (tensor<1xi32>, tensor<1xi32>) -> tensor<2xi32>
>     %1 = "stablehlo.dynamic_broadcast_in_dim"(%arg1, %0) {broadcast_dimensions = array<i64: 0, 1>} : (tensor<?x?xf32>, tensor<2xi32>) -> tensor<?x?xf32>
>     %2 = stablehlo.add %arg0, %1 : tensor<?x?xf32>
>     return %2 : tensor<?x?xf32>
>   }
> }
> 
> """
> 
> with ir.Context() as context:
>     register_dialect(context)
>     module = ir.Module.parse(module_str)
>     input1 = ir.DenseElementsAttr.get(np.random.random(size=(2, 2)).astype(np.float32))
>     input2 = ir.DenseElementsAttr.get(np.random.random(size=(1, 1)).astype(np.float32))
>     mlir_args = [input1, input2]
>     rets = eval_module(module, mlir_args)
>     print(rets)
> ```
> 
> might not face that particular issue as the [pass pipeline](https://github.com/openxla/stablehlo/blob/283f41ce1f2a623e99b73131debfcc76a5b7da16/stablehlo/transforms/PassPipelines.cpp#L32) which is baked into the `eval_module`, will reduce it into
> 
> ```
>  func.func @forward(%arg0: tensor<2x2xf32>, %arg1: tensor<1x1xf32>) -> tensor<2x2xf32> {
>     %0 = stablehlo.broadcast_in_dim %arg1, dims = [0, 1] : (tensor<1x1xf32>) -> tensor<2x2xf32>
>     %1 = stablehlo.add %arg0, %0 : tensor<2x2xf32>
>     return %1 : tensor<2x2xf32>
>   }
> ```

Got it. I will try `shape-legalize-to-stablehlo` first.
