### ISSUE TITLE
VhloToVersionPass to allow `current`  as a target version?

### ISSUE THREAD

**Issue by abhigunj** [openxla/stablehlo#2524]
VhloToVersionPass description (below) says target version can be `current` but the pass does not handle it. Should we support it or update the description to remove `current`?

```
def VhloToVersionPass : Pass<"vhlo-to-version"> {
  let summary = "Convert between versions of VHLO.";
  let options = [
    Option<"targetVersionOption", "target", "std::string", "",
           "The target version. Must be a version of the form #.#.# or 'current'.">,
  ];
}

```

**Comment by abhigunj** [comment]
cc: @GleasonK

**Comment by sdasgup3** [comment]
`current but does not handle it..`

Can you elaborate what you mean here?

**Comment by abhigunj** [comment]
> `current but does not handle it..`
> 
> Can you elaborate what you mean here?

`validateTargetVersion` does not allow `current` version. 
https://github.com/openxla/stablehlo/blob/main/stablehlo/transforms/VhloToVersion.cpp#L72C20-L72C41

validated with simple test module. `stablehlo-opt -vhlo-to-version='target=current' t1.mlir`.  Original pass was handling it, lateron particular code was removed.
