### ISSUE TITLE
Mismatch between specification and tests for quantized types

### ISSUE THREAD

**Issue by jtristan** [openxla/stablehlo#2539]
### What happened?

The tests in `stablehlo/stablehlo/tests/interpret` and `stablehlo/stablehlo/testdata` use a different syntax than what is described in the specification. Here is a grammar that describes the actual syntax of quantized types in those tests:

```
QuantizedTensorType ::= 'tensor' '<' Shape QuantizedTensorElementType '>'
QuantizedTensorElementType ::= '!quant.uniform' '<'
                  QuantizationStorageType
                  ['<' QuantizationStorageMin ':' QuantizationStorageMax '>']
                  ':' QuantizationExpressedType
                  [':' QuantizationDimension]
                  ',' QuantizationParameters '>'
QuantizationStorageType ::= IntegerType
QuantizationStorageMin ::= **IntegerLiteral**
QuantizationStorageMax ::= **IntegerLiteral**
QuantizationExpressedType ::= FloatType
QuantizationDimension ::= **IntegerLiteral**
QuantizationParameters ::= QuantizationParameter
                         | '{' QuantizationParameter {',' QuantizationParameter} '}'
QuantizationParameter ::= QuantizationScale **[ ':' QuantizationZeroPoint ]**
QuantizationScale ::= **FloatLiteral**
QuantizationZeroPoint ::= **IntegerLiteral**
```

where ** and ** emphasize where the differences with the specification are

**Comment by sdasgup3** [comment]
Dear @jtristan 
I am assuming that  you refer to the absence of the non terminals highlighted above. Please note that  `QuantizationStorageMin`, `QuantizationStorageMax`. If not present inferred from the storage type.
`QuantizationDimension` is relevant only for per-axis quantization and absent for per-tensor. 
`QuantizationDimension` is optional if the zero-point is zero. 

Please let me know if I am missing any discrepancies.

**Comment by jtristan** [comment]
No, the discrepancies are that the spec defines the grammar of `QuantizationStorageMin`, `QuantizationStorageMax`, `QuantizationDimension `, `QuantizationScale `, and `QuantizationZeroPoint ` respectively as `IntegerConstant `, `IntegerConstant `, `IntegerConstant `, `FloatConstant `, `IntegerConstant ` but that it should be `IntegerLiteral`, `IntegerLiteral`, `IntegerLiteral`, `FloatLiteral`, `IntegerLiteral` instead. Finally, the spec doesn't capture that `QuantizationZeroPoint ` is optional.

**Comment by sdasgup3** [comment]
Thanks for pointing those out. Will fix is asap.
