### ISSUE TITLE
Mismatch between specification and tests on literals

### ISSUE THREAD

**Issue by jtristan** [openxla/stablehlo#2544]
### What happened?

Some of the tests use literals of the form `array<type: elementLiterals>`, which are not described in the specification. [Example](https://github.com/openxla/stablehlo/blob/main/stablehlo/testdata/dynamic/arange_dynamic.mlir). If it helps, I could compile an exhaustive list of all the `tests/interpreter` and `testdata` where this happens, and the observed syntax.

**Comment by sdasgup3** [comment]
The wording used in the specification for such cases `slice_sizes | 1-dimensional tensor constant of type si64` is deliberate to keep the concern of specification separate from "potentially evolving" implementation (in this case how MLIR assembly printing is [handled](https://github.com/llvm/llvm-project/blob/ffeb793f3a90623ab3c7f33f922d48a1f5f97cdf/mlir/lib/IR/AsmPrinter.cpp#L2366)),  for "most" of the cases. That is one of the reason we avoided the use of `mlir::Attributes`   and used tensor constants instead.

**Comment by sdasgup3** [comment]
However, I agree that there should be minimal surprises between the specified grammar and their instances. IMO, a side note should be good for these where there might be multiple representation and chose a particular one (to avoid clutter and ambiguity).

**Comment by jtristan** [comment]
Well, it is not for me to decide how precise the specification should be. However, I'm compiling at list of all the literals I see in practice and I think it would not be too difficult to refine the specification to account for them. I propose that we close this issue and when I am done, I will try to provide a detailed grammar of the literals and you can decide whether or not it should be in the spec.

**Comment by sdasgup3** [comment]
That sounds like a plan. Looking forward to the revision. 
Closing for now.
