### ISSUE TITLE
Use verifyReducerShape in SortOp

### ISSUE THREAD

**Issue by zhouxin913** [openxla/stablehlo#257]
### Request description

Per discussion in https://github.com/openxla/stablehlo/pull/221#discussion_r987176440, consider reuse `verifyReducerShape` in SortOp, as SortOp also contains a region need to be check like other Reduce*Op. 
Need investigate in detail.

**Comment by zhouxin913** [comment]
Needs a revisit before EOM.

**Comment by zhouxin913** [comment]
[verifyReducerShape()](https://github.com/openxla/stablehlo/blob/main/stablehlo/dialect/TypeInference.cpp#L273) is now used by:
- ReduceOp
- ReduceWindowOp
- SelectAndScatterOp
- ScatterOp
- ReduceScatterOp

which check the args (both inputs and init) and return types of inner block of those ops.
However in `SortOp`, the verification of inner block is quite straightforward, includes 2 sections of code https://github.com/openxla/stablehlo/blob/main/stablehlo/dialect/TypeInference.cpp#L1167 and https://github.com/openxla/stablehlo/blob/main/stablehlo/dialect/TypeInference.cpp#L1188 which checks the args (no `inits`), and the return value: single 0-ranked tensor with element-type i1 instead of multiple complicate return values like `verifyReducerShape()`. 
So I believe the code in `inferSortOp()` now is simple and strong enough, and no need to twist with verifyReducerShape(). 
What do you think of it? @sdasgup3

**Comment by subhankarshah** [comment]
> 

I agree with @zhouxin913 we can simply close this issue if @sdasgup3 feels the same.

The code linked in the comment above refers to following commit version -
https://github.com/openxla/stablehlo/blob/8b49e34d73752d10d94d929a5952f4bbf3eb7f1d/stablehlo/dialect/TypeInference.cpp

**Comment by sdasgup3** [comment]
Thanks for the findings. 
Feel free to close this one.
