### ISSUE TITLE
TIMEOUT: igammac_float64_20_20_float64_20_20_chlo.mlir.test

### ISSUE THREAD

**Issue by apivovarov** [openxla/stablehlo#2590]
### What happened?

`igammac_float64_20_20_float64_20_20_chlo.mlir.test ` timed out if executed along with all other tests
```
bazel test //...
TIMEOUT: //stablehlo/testdata:igammac_float64_20_20_float64_20_20_chlo.mlir.test (Summary)
```

However, when run individually, it passes. Total time: 88 sec. Testing time: 53 sec
```
bazel test //stablehlo/testdata:igammac_float64_20_20_float64_20_20_chlo.mlir.test
INFO: Elapsed time: 88.440s, Critical Path: 78.23s
INFO: 2 processes: 2 processwrapper-sandbox.
INFO: Build completed successfully, 2 total actions
//stablehlo/testdata:igammac_float64_20_20_float64_20_20_chlo.mlir.test  PASSED in 53.6s
```

### Steps to reproduce your issue

```
bazel test //...

TIMEOUT: //stablehlo/testdata:igammac_float64_20_20_float64_20_20_chlo.mlir.test (Summary)
```

### Version information

e44958c8ac3178df0d69d46804960df8e92580b1

**Comment by GleasonK** [comment]
Update: Filtered tests to this bug ticket in https://github.com/openxla/stablehlo/pull/2586
