### ISSUE TITLE
Ops unexpectedly supporting boolean types in the ODS

### ISSUE THREAD

**Issue by sdasgup3** [openxla/stablehlo#262]
### Request description

This ticket will track the following 

https://github.com/openxla/stablehlo/pull/250#discussion_r986432897 
https://github.com/openxla/stablehlo/pull/240#discussion_r987531422 and
https://github.com/openxla/stablehlo/pull/250#discussion_r986436241

We have the following list of ops for which the  [StableHLO semantics](https://github.com/openxla/stablehlo/blob/main/docs/spec_draft.md)  does not support boolean type which seems expected.
However, the [StableHLO ODS](https://github.com/openxla/stablehlo/blob/main/stablehlo/dialect/StablehloOps.td)  and/or  the [HLO semantics](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/service/shape_inference.cc) differs in that respect. 

| Ops   | bool type supported in StableHLO semantics | bool type supported in ODS | bool type supported in HLO Semantics |
|-------|:---------------------:|:-----:|:---------------:|
| add | No                  | Yes | Yes           |
| multiply | No                  | Yes | Yes           |
| maximum | No                  | Yes | Yes           |
| minimum | No                  | Yes | Yes           |
| divide | No | Yes | No | 
| remainder | No |  Yes | No | 
| subtract | No | Yes | No | 

For the first 4 ops, StableHLO spec might support boolean types as well while clarifying the behavior in the spec.  
 - AddOp: ~For boolean the  behavior is like OrOp~ upd: The behavior like XorOp.
 -  MulOp: For boolean the  behavior is like AndOp
 -  Maximum/Minimum: For boolean the  behavior is `true` > `false`

For the others ODS might need to be updated.

**Comment by ghpvnist** [comment]
Can you also add a row for `abs` op?

**Comment by sdasgup3** [comment]
For abs op we have a separate [ticket](https://github.com/openxla/stablehlo/issues/263)

**Comment by burmako** [comment]
Remaining work: disallow `i1` in DivOp/RemOp/SubOp.
