### ISSUE TITLE
Supported type mismatch for AbsOp between spec and HLO semantics

### ISSUE THREAD

**Issue by sdasgup3** [openxla/stablehlo#263]
### Request description

Follow up on [comment ](https://github.com/openxla/stablehlo/pull/250#discussion_r986278277)

As per HLO semantics, AbsOp only supports signed integers, where the StableHLO semantics supports unsigned as well. The later added  because of the similarity of AbsOp with NegateOp for which HLO semantics[ supports both](https://github.com/tensorflow/tensorflow/blob/475c1da0dcd0a3b13b5631b1ded8aaf16802bd01/tensorflow/compiler/xla/service/shape_inference.cc#L307).

We might have to figure out if we should diverge from HLO?

**Comment by burmako** [comment]
"We might have to figure out if we should diverge from HLO?". For the initial version of the spec, I don't think we should diverge from HLO. Let's just align the StableHLO behavior with what HLO does and then think about changes after the spec is completed.
