### ISSUE TITLE
Incorrect help text for --stablehlo-legalize-to-linalg options

### ISSUE THREAD

**Issue by PerMildner** [openxla/stablehlo#2655]
### What happened?

The `--help` says there is a `--enable-primitive-ops` but that does not seem to be true:

```
$ stablehlo-opt --stablehlo-legalize-to-linalg --enable-primitive-ops 1> /dev/null < /dev/null
stablehlo-opt: Unknown command line argument '--enable-primitive-ops'.  Try: 'stablehlo-opt --help'
...
$ stablehlo-opt --help | grep -A 3 -e 'stablehlo-legalize-to-linalg'
      --stablehlo-legalize-to-linalg                         -   Legalize StableHLO to LinAlg
          --enable-primitive-ops                             - Lower to primitive Linalg ops (map, reduce and transpose) when possible, instead of linalg.generic
          --enable-sparse-ops                                - Lower to Sparse Tensor ops (sparse_tensor.concatenate)when possible, instead of linalg.generic
      --stablehlo-legalize-to-tosa                           -   Legalize StableHLO to TOSA

```
(I adjusted spacing to ensure it looks like in the terminal)

### Version information

e44958c8ac3178df0d69d46804960df8e92580b1

**Comment by sdasgup3** [comment]
Hi @PerMildner 
Can you please try out `stablehlo-opt  --stablehlo-legalize-to-linalg="enable-primitive-ops=true"`. Per [cs](https://github.com/openxla/stablehlo/blob/db2ce93922933fc21e17311b4b001c25b46024e7/stablehlo/conversions/linalg/transforms/Passes.td#L34), `enable-primitive-ops` is an option to `stablehlo-legalize-to-linalg`.

**Comment by PerMildner** [comment]
Thanks, `--stablehlo-legalize-to-linalg="enable-primitive-ops=true"` works, but that syntax is not mentioned in the `--help` output and the syntax that _is_ mentioned does not work.

**Comment by sdasgup3** [comment]
Thanks for conforming. The pass options are usually nested under the pass handle, like
```
--stablehlo-legalize-to-linalg                         -   Legalize StableHLO to LinAlg
          --enable-primitive-ops                             - Lower to primitive Linalg ops (map, reduce and transpose) when possible, instead of linalg.generic
          --enable-sparse-ops                                - Lower to Sparse Tensor ops (sparse_tensor.concatenate)when possible, instead of linalg.generic
```

**Comment by sdasgup3** [comment]
Let me close the issue for now. Feel free to back with follow-ups.

**Comment by PerMildner** [comment]
I do not understand why this was closed.

Currently the `--help` text is worse than nothing for those likely to read help texts.

**Comment by sdasgup3** [comment]
Please note that the syntax is part of the  MLIR's standard documentation on pass-pipeline expressions [doc](https://mlir.llvm.org/docs/PassManagement/#textual-pass-pipeline-specification). 

I am up for ways to improve the clarity of our documentation. In this instance, one option could be to make sure that the help text says that these are boolean options. Another could be to create a dedicated section in the help text for commonly used options along with their their syntax (Note: this could be overwhelming when applied uniformly to all the available passes).

In any case, please let me know if you have any suggestion on making the help text more informative.

**Comment by PerMildner** [comment]
I suspect the misleading hyphens before e.g. `--enable-primitive-ops` is generated from [the tablegen specification](https://github.com/openxla/stablehlo/blob/d1db6dfe13488b4735a6f08c324145625447fb6d/stablehlo/conversions/linalg/transforms/Passes.td#L35) (which does not use hyphens).

In that case the real problems is with the MLIR infrastructure, not really with StableHLO, and it would be hard to fix the `--help` text at your end.

So, perhaps closing as "not our fault:-)" is best (and hope I report this again as an MLIR bug).

**Comment by sdasgup3** [comment]
Sounds good!
Closing as "not our fault" :)
