### ISSUE TITLE
Move verifiers and shape functions to a separate file

### ISSUE THREAD

**Issue by zhouxin913** [openxla/stablehlo#270]
### Request description

There exist several shape functions in `StablehloOps.cpp` which need to be moved to `StablehloTypeInference.cpp` so that they can can be shared with MHLO. The expected timeline for this is end of Oct.

**Comment by burmako** [comment]
Work on this has started in https://github.com/openxla/stablehlo/pull/269.

**Comment by zhouxin913** [comment]
https://github.com/openxla/stablehlo/pull/269 is merged to main.
As bounded dynamism work is prioritized, the related ops will be moved accordingly as next batch.

**Comment by zhouxin913** [comment]
https://github.com/openxla/stablehlo/pull/269 is merged.
More ops will be moved later: the next batch is the ops which need bounded dynamism.

**Comment by zhouxin913** [comment]
This is now actively in progress and expected delivery date is EOY 2022.

**Comment by sdasgup3** [comment]
`CollectivePermuteOp` is another candidate for this refactoring. For example,
[verifyCollectivePermuteSourceTargetPairs](https://github.com/openxla/stablehlo/blob/c998e2dd65ff3487603e67a86d7d696f3984adc6/stablehlo/dialect/StablehloOps.cpp#L1469) should be moved to TypeInference.cpp  to be leveraged by both StableHLO and MHLO. [Here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/mlir_hlo/mhlo/IR/hlo_ops_common.cc#L27) is the sharing opportunity in MHLO.

**Comment by sdasgup3** [comment]
I am curious to know how are we going to decide on the amount of work (number of ops which might need the refactoring) needed here? 

We cannot rely on the status.md's "Type inference column" as the spec-wprkstream  does not include this refactoring aspect while resolving items in the column to a `yes`. 
@zhouxin913

**Comment by sdasgup3** [comment]
Just a thought: In order to avoid creating a checklist of all the ops, that we need to revisit for refactoring, we can take this up as an action item while doing the interpreter, which in any way needs revisit on an op-by op basis (The exact details are TBD).

**Comment by burmako** [comment]
#783 only fixed this partially, reopening for now.
