### ISSUE TITLE
update interpreter of add, multiply, maximum, and minimum w.r.t supporting bool type

### ISSUE THREAD

**Issue by sdasgup3** [openxla/stablehlo#285]
### Request description

Originated from https://github.com/openxla/stablehlo/pull/264#pullrequestreview-1131986897.

The spec of these ops are updated as part of https://github.com/openxla/stablehlo/pull/264. The issue is to update the interpreter.

**Comment by burmako** [comment]
Let's also include `multiply` here, since it's about to land.

**Comment by sdasgup3** [comment]
The multiply op will be taken care of by https://github.com/openxla/stablehlo/pull/240
