### ISSUE TITLE
Tighten the formal notation that we're using in the spec

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#289]
After all Data Movement and Reduction ops are specced, we should review and tighten our formal notation. Some stuff that has come up in the recent pull requests:
  * Make sure we define all metasyntactic variables and functions in advance, like `i`, `j`, `d`, `k`, `R`, `dim(...)`, `rank(...)`, `size(...)`, etc.
  * Consider using Latex syntax like $i_{d}$ instead of `id`.
  * Settle on using $\le$ vs `<=` (the former is not copypasteable).
  * Consistent syntax for stuff like "for all foo in bar" and "for any...".
  * When to use `[i0, ..., ik, ..., iR-1]` vs `[i0, ..., iR-1]` (or maybe even `[i0, ...]`).
  * "size(`operand`)" vs "`size(operand)`"

**Comment by sdasgup3** [comment]
For reverse op, we use "All dimensions in `dimensions` are unique."

In this context, we means that all the entries of `dimensions` (which logically specify dimensions) are unique.  IMO, this is a bit confusing with

```
For all dimensions `i` in `operand`
```
where we straightforwardly mean the dimensions of `operand`

Can we simplify the above by saying 

The elements of `dimensions` are unique.

**Comment by sdasgup3** [comment]
We might need to define the following items which are currently in use. 

* dim(x: tensor, y:int) as the dimension size of yth dimension of x
* size(x: 1-D tensor) = dim(x, 0)

**Comment by ghpvnist** [comment]
Unify the use of:
* 0 vs $0$
* = vs $=$ vs `=`

**Comment by ghpvnist** [comment]
Unrelated to formal notations, but I figured it's better to address here while going through all the notations:
We currently use new lines to express dimensions in the examples, but sometimes we do not introduce new lines.
Decide at which nth dimension we should not add new lines. For example:
```
[
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
]
```
vs
```
[
    [[1, 2],
     [3, 4]],
    [[5, 6],
     [7, 8]]
]
```
vs
```
[
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
]
```

**Comment by burmako** [comment]
How do we order constraints? Following the order in which underlying inputs/outputs are defined in ODS? What about constraints for the same inputs? Which ones go first?

**Comment by burmako** [comment]
Let's also consider drawing inspiration from NumPy's notation, since it's so prevalent: https://numpy.org/doc/stable/user/basics.indexing.html. It's okay if we decide to not use it or some parts of it - the use cases are fairly different - but I think we should definitely look into it.

**Comment by burmako** [comment]
To express "for all d in dimensions of operand", we could say "for d in axes(operand)".

**Comment by sdasgup3** [comment]
Consider adding a extra column in Tables under Inputs and Outputs section in order to specify  pointers to constraints, mentioned in Constraints section, for each input/output.

**Comment by sdasgup3** [comment]
Using `a` and `b` have same type 
Vs 
`type(a)` = `type(b)`

**Comment by sdasgup3** [comment]
dim(`a`, b) vs `dim(a,b)`. Same for other macros like `size`, `type`, `element-type`, `rank`.

**Comment by burmako** [comment]
`indices(tensor)` in the sense of "index space of `tensor` sorted lexicographically in ascending order".

**Comment by sdasgup3** [comment]
`of boolean type` (as in stablehlo.and/not/xor) VS  `of type i1` (other places)

**Comment by ghpvnist** [comment]
Repeating variable name and its meaning:
Apply X along the `dimensions` dimensions.

**Comment by burmako** [comment]
Another area of improvement: potentially using BNF notation. Will likely be a good fit for types and constants, but might not be worth the effort to define separate syntax for ops. Maybe fork MLIR generic syntax and turn that into BNF notation for ops?

**Comment by ghpvnist** [comment]
Decide whether to use hex representation or its real value in the mlir example. E.g.:
```mlir
// %operand: [0xFF800000, 0x7F800000, 0xFFFFFFFF, 0x7FFFFFFF]
```
vs

```
// %operand: [-inf, inf, -nan, nan]
```

**Comment by bhack** [comment]
> // %operand: [-inf, inf, -nan, nan]

It is more readable for the avg user.

**Comment by burmako** [comment]
Decide whether to use decimal or binary representation for integer arguments to ops like `shift_left` or `and`.

**Comment by burmako** [comment]
"array of si64" vs "tensor constant of type si64" vs "tensor constant of si64".

**Comment by burmako** [comment]
`%results:N` vs `%results0, %results1, ...`.

**Comment by sdasgup3** [comment]
As discussed in [here](https://github.com/openxla/stablehlo/pull/510#discussion_r1038384863), the type of `replica_groups` input for Collective Ops can be better specified as `variadic number of 1-dimensional tensor constants of type si64`. However, the macro,  like `size` and `index`, that we are using for specifying  constraints related to `replica_groups` are bit confusing as they have been used consistently in the spec with tensor types. This need to be addressed.

**Comment by burmako** [comment]
`split(tensor, num_parts, dimension)` turned out to be very useful for a few ops, so let's promote it to a meta-function, so that we don't have to implement it every time.

**Comment by burmako** [comment]
Same for `permute`.

**Comment by sdasgup3** [comment]
For dynamic_slice, consider replacing 

`clamp(0, start_indices, shape(operand) - slice_sizes)`
to
` clamp(broadcast_in_dim(0, [], shape(operand) - slice_sizes), start_indices, shape(operand) - slice_sizes)`


Same for dynamic_update_slice.

**Comment by burmako** [comment]
`value.real` vs `real(value)`.

**Comment by burmako** [comment]
`slice` in AllToAllOp's spec can most likely be simplified to `split`.

**Comment by burmako** [comment]
Explain the flavor of EBNF that we're using.

**Comment by ghpvnist** [comment]
Can the constraints be implied from existing constraints? For example, ConcatenateOp does not allow rank-0 inputs to be concatenated. Should this be explicitly written or implied from, say C4 okay?

**Comment by sdasgup3** [comment]
Address how `clamp` op is used in the formulation of `dynamic_slice and dynamic_update_slice`.  https://github.com/openxla/stablehlo/pull/1040#discussion_r1095085159

**Comment by ghpvnist** [comment]
If/Case ops have constraints like:
```
* (C3) For all `i`, `type(results[i]) = type(true_branch).outputs[i]`.
```
Standardize what it means to have `.outputs` and whether it should be written as `type(true_branch.outputs[i])`.

**Comment by burmako** [comment]
Would be good to decide on not using vs using operator overloading in describing semantics of ops in terms of other ops.

1\) Not using operator overloading:
```Python
def batch_norm_inference(operand, scale, offset, mean, variance, epsilon, feature_index):
  # Broadcast inputs to shape(operand)
  scale_bcast = broadcast_in_dim(scale, [feature_index], shape(operand))
  offset_bcast = broadcast_in_dim(offset, [feature_index], shape(operand))
  mean_bcast = broadcast_in_dim(mean, [feature_index], shape(operand))
  variance_bcast = broadcast_in_dim(variance, [feature_index], shape(operand))
  epsilon_bcast = broadcast_in_dim(constant(epsilon), [], shape(operand))

  # Perform normalization using the provided `mean` and `variance` instead of
  # computing them like `batch_norm_training` does.
  centered_operand = subtract(operand, mean_bcast)
  stddev = sqrt(add(variance_bcast, epsilon_bcast))
  normalized_operand = divide(centered_operand, stddev)
  return add(multiply(scale_bcast, normalized_operand), offset_bcast)
```

2\) Using operator overloading:
```
* For quantized types:
  * `float_result = (lhs - zero_point(lhs)) * scale(lhs) +
    (rhs - zero_point(rhs)) * scale(rhs)`.
  * `rounded_result = round_nearest_even(float_result / scale(result))`.
  * `result = clamp(storage_min(result), rounded_result + zero_point(result), storage_max(result))`.
```

**Comment by sdasgup3** [comment]
Augment the spec with the macros/functions  used for `scale(...), zero_point(...), quantization_dimension(...)`.

**Comment by burmako** [comment]
MapOp, ReduceOp, ScatterOp and SortOp are currently using the ellipsis syntax in an unconventional way. E.g. the spec for MapOp says `result[result_index] = computation(inputs...[result_index])`. However, `computation` doesn't take one parameter which is a list of scalars - instead it takes multiple scalar parameters. We should straighten this out.

**Comment by burmako** [comment]
We are currently using the same notation for both tensors and lists, whereas the two are not exactly the same thing.

**Comment by burmako** [comment]
Follow up on https://github.com/openxla/stablehlo/pull/1556#discussion_r1213841391.

**Comment by burmako** [comment]
https://github.com/openxla/stablehlo/pull/1556 has just landed which resolves most of the comments in this ticket (I marked them with the 🚀 emoji). I also went through the remaining comments and moved them to new tickets. Will be closing this ticket now.
