### ISSUE TITLE
Remove additional builder methods for AllGatherOp and ReduceScatterOp

### ISSUE THREAD

**Issue by GleasonK** [openxla/stablehlo#298]
### Request description

Remove unnecessary builder methods, propagate changes from MHLO to StableHLO:
https://github.com/tensorflow/mlir-hlo/commit/44ffec7bce15ef17f5264aadc36f3c6e89642d8a

**Comment by ghpvnist** [comment]
Closing ticket since no action seems necessary for this change as we don't have builders for these ops.
