### ISSUE TITLE
Add verification for SortOp

### ISSUE THREAD

**Issue by subhankarshah** [openxla/stablehlo#321]
### Request description

Add verification for following cases of SortOp -
  * Variadic tensor `inputs` should have at least 1 tensor

**Comment by zhouxin913** [comment]
I think ODS does not allow Variadic to me empty: it will error out so I removed the check of it in https://github.com/openxla/stablehlo/pull/221/files#diff-2c2e4d1dc1c94578a79c612478b15fcb69b5eda6c5df624f5d91d8bdefdc0641L4893
```
  Operation::operand_range operands = this->getInputs();
  if (operands.empty()) return emitOpError("requires at least one input");
```
Which means that we don't check it ourselves, as ODS check it already. What do you think of it?

**Comment by burmako** [comment]
Nice find! The verification is coming from [`[SameOperandsAndResultShape]`](https://github.com/llvm/llvm-project/blob/main/mlir/lib/IR/Operation.cpp#L837-L839), but yeah - it looks like it's already covered.

```
$ cat ~/example.mlir
func.func @main() {
  "stablehlo.sort"() ({
    ^bb0():
      %result = stablehlo.constant dense<true> : tensor<i1>
      "stablehlo.return"(%result) : (tensor<i1>) -> ()
  }) {
    dimension = 0 : i64,
    is_stable = true
  } : () -> ()
  func.return
}

$ build/bin/stablehlo-opt ~/example.mlir
/usr/local/google/home/burmako/example.mlir:2:3: error: 'stablehlo.sort' op expected 1 or more operands, but found 0
  "stablehlo.sort"() ({
  ^
/usr/local/google/home/burmako/example.mlir:2:3: note: see current operation:
"stablehlo.sort"() ({
  %0 = "stablehlo.constant"() {value = dense<true> : tensor<i1>} : () -> tensor<i1>
  "stablehlo.return"(%0) : (tensor<i1>) -> ()
}) {dimension = 0 : i64, is_stable = true} : () -> ()
```
