### ISSUE TITLE
Migrate all uses of -1 to kDynamicSize

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#327]
See https://discourse.llvm.org/t/rfc-unify-kdynamicsize-and-kdynamicstrideoroffset/64534 for the motivation. We're in a pretty good shape with respect to that, but cursory investigation reveals that we're still using -1 in a few places.

**Comment by GleasonK** [comment]
Added some changes in #569

I see two remaining tasks after that PR is submitted:
1. Fix any Attributes that have printer/parser that relies on the value of `kDynamicSize`, such as gather.
2. Go through the existing error messages and check if any leak the value of `kDynamicSize`.

**Comment by burmako** [comment]
Let's also change all references to `kDynamicSize` to `kDynamic`. In #577, I did that for references in code, but it looks like there are some references in comments which I missed.

**Comment by burmako** [comment]
Implemented in https://github.com/openxla/stablehlo/pull/569.
