### ISSUE TITLE
FFTOp unexpectedly allows 0-dimension `operand`

### ISSUE THREAD

**Issue by ghpvnist** [openxla/stablehlo#382]
### What happened?

Current code in [StablehloOps.cpp](https://github.com/openxla/stablehlo/blob/4152bb871975ee1575071808a02b144dea80d951/stablehlo/dialect/StablehloOps.cpp#L752-L755) checks whether the rank is between [0, 3] using `fft_length.size()`. This hides bugs where the `operand` is of rank 0 but with `fft_length.size()` between [0, 3].

### Steps to reproduce your issue

Expected:
```
rank must be between 1 and 3, but got 0.
```

Actual:
Verify passes.

An example program in MHLO:
```
func.func @main() -> tensor<4xcomplex<f32>> {
  %0 = mhlo.constant dense<> : tensor<0xcomplex<f32>>
  %1 = "mhlo.fft"(%0) {
    fft_length = dense<[1]> : tensor<1xi64>,
    fft_type = #mhlo<fft_type FFT>
  } : (tensor<0xcomplex<f32>>) -> tensor<0xcomplex<f32>>
  return %1 : tensor<0xcomplex<f32>>
}
```

**Comment by burmako** [comment]
`tensor<0xcomplex<f32>>` is a rank-1 tensor.

```
func.func @main() -> tensor<complex<f32>> {
  %0 = mhlo.constant dense<(0.0, 0.0)> : tensor<complex<f32>>
  %1 = "mhlo.fft"(%0) {
    fft_length = dense<[1]> : tensor<1xi64>,
    fft_type = #mhlo<fft_type FFT>
  } : (tensor<complex<f32>>) -> tensor<complex<f32>>
  return %1 : tensor<complex<f32>>
}
```

produces the expected error: "error: operand rank must not be less than fft rank of 1 for operand of type 'tensor<complex<f32>>'".
