### ISSUE TITLE
Verify `window_reversal` in ConvolutionOp

### ISSUE THREAD

**Issue by sdasgup3** [openxla/stablehlo#399]
The [window_reversal attribute](https://github.com/openxla/stablehlo/blob/885b8e32afbb57bc1ee8a148420f609716440d54/stablehlo/dialect/StablehloAttrs.td#L196) does not have any verification check. 

This should be a 1-D tensor such that size(`window_reversal`) == number of spatial dims.

**Comment by sdasgup3** [comment]
The check on the StableHLO side will be addressed in https://github.com/openxla/stablehlo/pull/441

**Comment by subhankarshah** [comment]
@sdasgup3 can we close this?

**Comment by sdasgup3** [comment]
I think so given that [both](https://github.com/openxla/stablehlo/issues/399#issuecomment-1306359885) the action items are addressed.
