### ISSUE TITLE
Warning spew

### ISSUE THREAD

**Issue by silvasean** [openxla/stablehlo#444]
### What happened?

```
/usr/local/google/home/silvasean/pg/torch-mlir/torch-mlir/externals/mlir-hlo/stablehlo/stablehlo/dialect/ChloOps.cpp:318:42: warning: extra ';' outside of a function is incompatible with C++98 [-Wc++98-compat-extra-semi]
BROADCAST_BINARY_OP_DEFS(BroadcastZetaOp);
                                         ^
```
And various other similar warnings

### Steps to reproduce your issue

Build with Clang with default warning settings (I think; or add -Wc++98-compat-extra-semi if necessary).

### Version information

mlir-hlo @ 36238f16441cd1a884af988d4400d2ebb0c75bbc

**Comment by GleasonK** [comment]
Curious what your build warning flags are? 

We currently use `-Wall` in CI, and build will pass with `-Wall -Wextra`, but not `-Weverything` largely due to C++98 incompats. I'm surprised we care about C++98 compat flags, given the amount of c++98 incompatible features we use, to show a few:

```
/usr/local/google/home/gleasonk/Coding/llvm-project/llvm/include/llvm/Support/ErrorHandling.h:121:73: error: 'nullptr' is incompatible with C++98 [-Werror,-Wc++98-compat]
llvm_unreachable_internal(const char *msg = nullptr, const char *file = nullptr,
                                                                        ^
...
/usr/local/google/home/gleasonk/Coding/llvm-project/llvm/include/llvm/Support/PointerLikeTypeTraits.h:75:10: error: 'constexpr' specifier is incompatible with C++98 [-Werror,-Wc++98-compat]
  static constexpr int NumLowBitsAvailable = 2;
         ^
```

Happy to include the `-Wc++98-compat-extra-semi` in build, but trying to figure out where to draw the line on the definition of a "warning free build".

**Comment by silvasean** [comment]
Oh, fascinating! This is part of the default LLVM build flags.

LLVM_ENABLE_PEDANTIC (default ON) leads to this piece of code which appears to normalize warning about the extra semicolons across GCC and clang:
https://github.com/llvm/llvm-project/blob/c37f29c49ea237eaf65dd137bffc1f3316f82951/llvm/cmake/modules/HandleLLVMOptions.cmake#L712

Maybe the takeaway here is to build with -pedantic and use -Wc++98-compat-extra-semi to smooth across GCC/Clang differences like LLVM does?

I'm curious -- does StableHLO have any CI that builds with CMake nested within an LLVM build? That seems like it will be a common configuration for users and could catch this.

**Comment by GleasonK** [comment]
We do not, that's a great suggestion though! I'll create a new task to add CI build with CMake nested in an LLVM build.

Will clean up the pedantic errors in the meantime to close this issue.
