### ISSUE TITLE
Move MHLO machinery for printing array refs into AssemblyFormat

### ISSUE THREAD

**Issue by GleasonK** [openxla/stablehlo#485]
### Request description

Found in #403. Move printing machinery for array refs to `AssemblyFormat.h`. Currently we have `printDenseI64Array`, which works for `I64ElementsAttr` and `BroadcastDimsAttr` but not for `def StableHLO_Dim : ArrayRefParameter<"int64_t", "Dimension">;`

As a follow-up change the HLODim printing to use this new functionality as suggested in #403.

**Comment by burmako** [comment]
Once done, let's use the new assembly format in `OutputOperandAlias`. See #403 for context.

**Comment by burmako** [comment]
The migrate from MHLO part is done in https://github.com/openxla/stablehlo/pull/546, which has just been merged. As discussed, there's still the matter of sharing this machinery with MHLO via `AssemblyFormat.h`.

**Comment by GleasonK** [comment]
Fixed in https://github.com/tensorflow/mlir-hlo/commit/c1f1538a2cc3f7508842403f6f6f13ce52d8834f
