### ISSUE TITLE
Consider removing dimensions from MapOp

### ISSUE THREAD

**Issue by ghpvnist** [openxla/stablehlo#487]
MapOp has `dimensions` attributes which is not used by the op currently since it only supports scalar map functions. Currently, all dimensions need to be provided, but there is no benefit in having them.

**Comment by burmako** [comment]
For the record, [hlo_instruction.cc](https://github.com/tensorflow/tensorflow/blob/ae7ef87bc75228bdd78f21167e6c3f765bb30118/tensorflow/compiler/xla/hlo/ir/hlo_instruction.cc#L372-L377) doesn't support `dimensions`.

**Comment by GleasonK** [comment]
Closing in favor of https://github.com/openxla/stablehlo/issues/2340 which proposes to remove MapOp all together
