### ISSUE TITLE
Tighten the verifier checks for AllGather

### ISSUE THREAD

**Issue by sdasgup3** [openxla/stablehlo#491]
### Request description

The missing check available in HLO: https://github.com/tensorflow/tensorflow/blob/c9d57288fe985527b85ed554a1d518b9ca03fc25/tensorflow/compiler/xla/service/shape_inference.cc#L2087

This will be handled in https://github.com/openxla/stablehlo/issues/462

**Comment by sdasgup3** [comment]
Closing this as it is alreqady handled as partof https://github.com/openxla/stablehlo/blob/283702a1378d4319b0ac551c3b4502a8e22bc386/stablehlo/dialect/StablehloOps.cpp#L1972

**Comment by burmako** [comment]
It looks like `operandType.isDynamicDim(allGatherDimIndex)` will crash if `allGatherDimIndex >= operandType.getRank()`, which is probably not we want from a verifier?

**Comment by sdasgup3** [comment]
I agree with you. Reopened.

**Comment by sdasgup3** [comment]
Also include checks to valid the shape of the return type which is missing as well leading to the following to pass

```
func.func @main(%arg0: tensor<128x100x32xf32>) -> tensor<128x100xf32> {
  %0 = "stablehlo.all_gather"(%arg0) {
    all_gather_dim = 0 : i64,
    channel_handle = #stablehlo.channel_handle<handle = 1, type = 0>,
    replica_groups = dense<[[0, 2, 4, 6], [1, 3, 5, 7]]> : tensor<2x4xi64>
  } : (tensor<128x100x32xf32>) -> tensor<128x100xf32>
  func.return %0 : tensor<128x100xf32>
}
```
