### ISSUE TITLE
Tighten verification check for ComplexOp

### ISSUE THREAD

**Issue by ghpvnist** [openxla/stablehlo#492]
### What happened?

There is no verification check that `lhs` and `rhs` need to have the same floating-point element type.

### Steps to reproduce your issue

This StableHLO program passes stablehlo-opt:
```
module @main {
  func.func @main() -> tensor<complex<f32>> {
    %0 = stablehlo.constant dense<1.0> : tensor<f32>
    %1 = stablehlo.constant dense<2.0> : tensor<f64>
    %2 = "stblehlo.complex"(%0, %1) : (tensor<f32>, tensor<f64>) -> tensor<complex<f32>>
    return %2 : tensor<complex<f32>>
  }
}
```

**Comment by burmako** [comment]
```
$ build/bin/stablehlo-opt ~/example.mlir
~/example.mlir:5:10: error: 'stablehlo.complex' op requires the same element type for all operands
    %2 = "stablehlo.complex"(%0, %1) : (tensor<f32>, tensor<f64>) -> tensor<complex<f32>>
         ^
```

ComplexOp's has `SameOperandsElementType` in its trait list, so this is already implemented: https://github.com/openxla/stablehlo/blob/283702a1378d4319b0ac551c3b4502a8e22bc386/stablehlo/dialect/StablehloOps.td#L717-L718.
