### ISSUE TITLE
Audit and fix type inference

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#5]
When bootstrapping StableHLO from MHLO, we have inherited MHLO's implementation of type inference. It already has significant coverage of the opset, but there's still plenty to do to review the existing implementations for completeness and provide new implementations where none exist. Let's figure out how to track this work and get to comprehensive coverage.

**Comment by zhouxin913** [comment]
[status.md](https://github.com/openxla/stablehlo/blob/main/docs/status.md) landed yesterday, and this is where I'll keep track of the status of verification / shape inference. I'll close this ticket for now and will open individual tickets / pull requests for individual ops as needed.
