### ISSUE TITLE
Revisit verification to DynamicUpdateSliceOp

### ISSUE THREAD

**Issue by ghpvnist** [openxla/stablehlo#554]
Current verification only checks that the start indices must have the same element type, but the remaining checks are missing. See constraints in #553.

**Comment by sdasgup3** [comment]
https://github.com/openxla/stablehlo/blob/4aff405bc1936e4121d25d2cd674166275f9c4e1/stablehlo/dialect/StablehloOps.td#L1570

We should check that the the element type of individual start_indices are i64.

**Comment by sdasgup3** [comment]
Please have a look at https://github.com/openxla/stablehlo/issues/557 to reconsider some of the checks.

**Comment by ghpvnist** [comment]
Closing this issue since it's decided that `start_indices` should be integer type. The remaining checks missing should be covered in type inference.
