### ISSUE TITLE
Verify that start_indices have the same type in DynamicSliceOp

### ISSUE THREAD

**Issue by ghpvnist** [openxla/stablehlo#557]
~Current verification does not check that `start_indices` is in bounds and whether `start_indices` combined with `slice_sizes` is also in range. See constraints in #556.~

~As commented below, the element type of individual `start_indices` should be `i64`.~

`start_indices` should all have the same type since during discussion below, it's decided that they should be integer type. Verification is set to `revisit` in #556.

**Comment by sdasgup3** [comment]
From https://github.com/openxla/stablehlo/pull/556#discussion_r1024712878

As `start_indices` are dynamic inputs we cannot verify any property related to the value of start_indices. Maybe we can close this?

**Comment by sdasgup3** [comment]
https://github.com/openxla/stablehlo/blob/4aff405bc1936e4121d25d2cd674166275f9c4e1/stablehlo/dialect/StablehloOps.td#L1536

We should check that the the element type of individual start_indices are `i64`.

**Comment by burmako** [comment]
As discussed in the PR, I don't think that indices should have element type `si64`. However, we should check that all of them have the same element type. Due to some reason, this is checked for `dynamic_update_slice`, but not for `dynamic_slice`.
