### ISSUE TITLE
Consider removing compare_type from CompareOp

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#584]
This is how things have been working [in HLO](https://github.com/tensorflow/tensorflow/blob/3451f5d39ea8add4c254acc9615d62ff589259b8/tensorflow/compiler/xla/comparison_util.h#L71-L79) since recently.

**Comment by GleasonK** [comment]
This op is used in production, and serialized for on-device consumption. As such (And given that the HLO representation is entirely different than this single enum), this op will be changed on an as-needed basis via RFC.
