### ISSUE TITLE
Spec quantization

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#588]
This will involve documenting: 1) a representation for quantized tensors, 2) UniformQuantizeOp, 3) UniformDequantizeOp, 4) which of the existing ops can take quantized tensors and how their semantics changes from that.

**Comment by burmako** [comment]
Similarly to the discussion in #8, the current plan is to wait until: 1) we finish speccing statically-shaped StableHLO ops, 2) we formalize syntax and maybe even evaluation of StableHLO programs (#484). Once that's done, I'm planning to provide a delta to this formalism that adds support for quantization. I think this won't be too hard and will result in a higher-quality design, because we'll be forced to explore more details.

**Comment by burmako** [comment]
See https://github.com/openxla/stablehlo/pull/1149 for a proposal for how to spec quantization in StableHLO in the context of alignment with TOSA.

**Comment by subhankarshah** [comment]
https://github.com/subhankarshah/stablehlo/blob/spec-quantization/docs/spec.md
Draft spec for quantization.

**Comment by ghpvnist** [comment]
[Action Item]: Verify the element-type of return value in `inferConvolutionOp` in `TypeInference.cpp` as noted in https://github.com/openxla/stablehlo/pull/1314#discussion_r1134489339

**Comment by mahmoud-abuzaina** [comment]
@subhankarshah when will the UniformQuantizeOp be specced? I am wondering what rounding modes will be supported in that op?

**Comment by sdasgup3** [comment]
Hi @mahmoud-abuzaina Thanks for your interest!
We are currently exploring options around speccing ops with quantized types: determining constraints on quantization parameters, types including the rounding mode involved during quantization. You can expect relevant PRs started pouring pouring in for review in Q1'23 and early Q2'23.

**Comment by sdasgup3** [comment]
Thanks @jon-chuang for your sharing your interest  and I am super excited to explore together. A few clarification questions:

1. Do you expect the source llama model to be in C++ or it is OK for the model to be expressed using other frameworks  like PyTorch?
2. Are you also interested in exploring the performance numbers  in platforms other than CPU?

**Comment by jon-chuang** [comment]
> Do you expect the source llama model to be in C++ or it is OK for the model to be expressed using other frameworks like PyTorch

The answer should be anything that can be lowered to HLO, including pytorch, onnx etc. Llama weights I think is originally pytorch/huggingface.

> Are you also interested in exploring the performance numbers in platforms other than CPU?

It's unclear at the moment. For instance, int4 quantization is not rly meaningful for GPU to my understanding due to lack of int4 matmul units and high overhead.

**Comment by sdasgup3** [comment]
Thanks for the clarification. Let me get back on this.

**Comment by sdasgup3** [comment]
Hi @jon-chuang 

Overall, `e2e example for llama and related models utilizing a StableHLO quantized matmul ` is very exciting to have and we have actively started working on gathering what's needed in StableHLO to represent quantization in cutting-edge LLMs (https://github.com/openxla/stablehlo/issues/1491). Feel free to have an eye on future updates. 

On a side note: While exploring on it, I found a few interesting and relevant discussions in [discord#jax](https://discord.com/channels/689900678990135345/821885387655479326/1111341878932160562) which you might  be interested in.

**Comment by sdasgup3** [comment]
Hello All
With reduction based operations we are planning to close this current issue related to quantization specification.  The remaining items are:
  1. [Action Item]: Verify the element-type of return value in inferConvolutionOp in TypeInference.cpp as noted in https://github.com/openxla/stablehlo/pull/1314#discussion_r1134489339
  2.   See https://github.com/openxla/stablehlo/pull/1149 for a proposal for how to spec quantization in StableHLO in the context of alignment with TOSA.
  3.   e2e example for llama and related models utilizing a stableHLO 

We are planning to open separate tickets for (1) and (2). Regarding (3), we are having some ongoing work in exporting quantized PyTorch models to StableHLO (ref)[https://github.com/pytorch/xla/pull/5763].  We will be happy to understand/address any  specific quantization specification in separate tickets.

**Comment by sdasgup3** [comment]
We have added https://github.com/openxla/stablehlo/issues/1896 and https://github.com/openxla/stablehlo/issues/1898 to track 1 and 2 resp. With that we are closing the current ticket.
