### ISSUE TITLE
Consider moving sparsity information into TypeExtensions

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#591]
At the moment, both bounds and sparsity are modelled via encodings (`TypeExtensions` and `SparseTensorEncoding` correspondingly). This means that we cannot have sparse tensors with bounds. Let's address this.

**Comment by GleasonK** [comment]
This issue will be resolved by https://github.com/openxla/stablehlo/issues/1078.

A future RFC on sparsity will propose a concrete design. We can consider issues like this as a part of this design.
