### ISSUE TITLE
Standardize summaries

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#611]
We've got `let description` in the ODS under control thanks to [the checklist](https://github.com/openxla/stablehlo/blob/main/docs/spec_checklist.md), but `let summary` is still inconsistent across ops.

**Comment by sdasgup3** [comment]
For any operation definition 
`def_StableHLO_XYZOp `, let us use the summary as 
```
let summary = "XYZ operator";
```

Note: 
1. Consistent across ops definitions
2. As the description is already load bearing, we can avoid re-inventing summary text for each op.  
3. Most of the ops definitions are already following the norm.
4. Some ops like rng deviates from the norm. 
```
let summary = "RNG operator with uniform or normal distribution.".
```

In such cases, we can choose to follow (1) OR make exceptions if the summary provides information which is (A) correct, and (B) is not repeated verbatim in description including the link to spec.

I vote for (1) as that way there less maintenance: One less thing to worry if op semantics changes.

**Comment by burmako** [comment]
LGTM, except that "operator" isn't currently a thing - neither in [the spec](https://github.com/openxla/stablehlo/blob/main/docs/spec.md) nor in [MLIR Language Reference](https://mlir.llvm.org/docs/LangRef/) which we use for inspiration for many things. How about "XYZ operation"?

**Comment by sdasgup3** [comment]
makes sense.
LGTM

**Comment by burmako** [comment]
Assigned this ticket to myself by mistake. It will be fixed anyway over time via https://github.com/openxla/stablehlo/blob/main/docs/reference_checklist.md.
