### ISSUE TITLE
Verify layout in InfeedOp

### ISSUE THREAD

**Issue by sdasgup3** [openxla/stablehlo#639]
Missing the following check:

The size of layout entry for each operand should match the rank of the operand.

https://github.com/tensorflow/tensorflow/blob/094de67f996da201f89ceb33416ce0449b271c78/tensorflow/compiler/xla/translate/mhlo_to_hlo/mlir_hlo_to_hlo.cc#L2316

https://github.com/openxla/stablehlo/issues/629 is related as that will decide if we should support layout in StableHLO and how to model them.

**Comment by sdasgup3** [comment]
FYI:
The following checks are already available in the verifier, but need to be revisited based on any revision of layout's implementation.

  *  size(`layout`) $=$ size(`results`) - 1.
  *  size(`layout[i]`) $=$ rank(`results[i]`) for all i $\in$ [0,size(`layout`)).

**Comment by burmako** [comment]
Closing in favor of #629. In the corresponding spec PR, we have decided to not spec layouts for InfeedOp, so I imagine that before we fix layout verification for InfeedOp, we'll need to rationalize it (via #629) in the first place.
