### ISSUE TITLE
Consider adding layout to collective ops

### ISSUE THREAD

**Issue by sdasgup3** [openxla/stablehlo#644]
### Request description

From [xla_builder.h](https://github.com/tensorflow/tensorflow/blob/5631d0d1d017eff1d1a54e32f76ef56f8ca04a8a/tensorflow/compiler/xla/client/xla_builder.h#L810-L815), HLO's AllGatherOp is allowing the producers to specific layout. The ticket will explore the need of representing the  layout field in StableHLO? 

The issue is originated [here](https://github.com/openxla/stablehlo/pull/503/files#r1032727716).

**Comment by burmako** [comment]
Also see similar feature requests for other collective ops linked above.

**Comment by burmako** [comment]
I think OutfeedOp might have layout as well: https://github.com/tensorflow/tensorflow/blob/1d69ba72834b963b72075a82c10959f6bb74e473/tensorflow/compiler/xla/service/hlo_verifier.cc#L849-L859. Generally speaking, it would be good to audit all ops and see which ones could need layout for feature parity with HLO.

**Comment by burmako** [comment]
Closing in favor of #629.
