### ISSUE TITLE
Consider adding layout to AllToAllOp

### ISSUE THREAD

**Issue by sdasgup3** [openxla/stablehlo#653]
### Request description

From [xla_builder.h](https://github.com/tensorflow/tensorflow/blob/5631d0d1d017eff1d1a54e32f76ef56f8ca04a8a/tensorflow/compiler/xla/client/xla_builder.h#L832-L835), AllToAllOp is allowing the producers to specific layout. The ticket will explore the need of representing the  layout field in StableHLO.

The issue is originated [here](https://github.com/openxla/stablehlo/pull/555#discussion_r1032847711)

**Comment by burmako** [comment]
Superseded by #644.
