### ISSUE TITLE
Add versioned CHLO ops to VHLO

### ISSUE THREAD

**Issue by GleasonK** [openxla/stablehlo#678]
### Request description

VHLO (Versioned StableHLO, https://github.com/openxla/stablehlo/pull/278) currently only has versioned ops for StableHLO, but we want to provide stability guarantees for StableHLO and CHLO. Eventually CHLO ops will need to be added to the opset.

**Comment by burmako** [comment]
[The current thinking](https://github.com/openxla/stablehlo/issues/602#issuecomment-1413110024) is that we might not necessarily want to have a spec and compatibility guarantees for CHLO. Instead, we would just decompose CHLO ops into StableHLO ops before serialization. Given that, I'll close this ticket for now until we have a resolution in #602.
