### ISSUE TITLE
Create scalable test plan for VHLO

### ISSUE THREAD

**Issue by GleasonK** [openxla/stablehlo#679]
### Request description

VHLO (Versioned StableHLO, https://github.com/openxla/stablehlo/pull/278) currently has very few upgrade / downgrade passes to test, so the current test infrastructure works, but more needs to be done to make it easy to scale as the dialect evolves.

See discussion in: https://github.com/openxla/stablehlo/pull/278#discussion_r1033036219

**Comment by burmako** [comment]
The "Tests" section in https://github.com/openxla/stablehlo/blob/main/docs/compatibility.md goes into details of the ongoing compatibility testing, and the "Future work" section outlines plans for future improvements.
