### ISSUE TITLE
Add inferReturnTypes for PartitionIdOp

### ISSUE THREAD

**Issue by GleasonK** [openxla/stablehlo#683]
### Request description

Now that we have `PartitionIdOp` (#673), consider adding support for inferReturnTypes using a similar method as ReplicaIdOp.

Port of: https://github.com/tensorflow/mlir-hlo/commit/1734d3848cfdef50bd000ff735f8b29821a4aba1
> Add `inferReturnTypes` for PartitionIdOp.
> Same as what already exists for ReplicaIdOp.

**Comment by burmako** [comment]
Fixed in https://github.com/openxla/stablehlo/pull/673.
