### ISSUE TITLE
Create a skeleton of the interpreter

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#7]
Let's opensource the internal skeleton of the StableHLO interpreter. Following up on that, we'll be creating individual tickets for individual ops to keep track of the ongoing work (perhaps, jointly with spec tickets for individual ops).

**Comment by sdasgup3** [comment]
This issue would be preceded by the switch to signed-ness semantics https://github.com/openxla/stablehlo/issues/22.

**Comment by fortianyou** [comment]
Hi @burmako, does it mean that stablehlo will have a runtime? With the interpreter, will XLA or any other compiler be required to run stablehlo module?

**Comment by burmako** [comment]
Hi @fortianyou! The idea is for this interpreter to serve as the reference implementation of StableHLO which accompanies the spec. It would also be nice to use it for constant folding and/or partial evaluation at compile time, but that'll need further design discussion which has started in #44. We don't have other use cases planned for the interpreter at the moment.

> does it mean that stablehlo will have a runtime? With the interpreter, will XLA or any other compiler be required to run stablehlo module?

At the moment, StableHLO is positioned as "an operation set that expresses ML computations" and "a portability layer between ML frameworks and ML compilers". Within that positioning, StableHLO doesn't have an opinion on how it's executed beyond providing specs for individual ops, and it's up to individual consumers to decide how to compile StableHLO, what runtime to use together with that, etc.

At [the OpenXLA community meeting on 8/9](https://github.com/openxla/community/tree/main/meetings/20220809-community-meeting), we talked a bit about "framework optionality" and "hardware optionality" as important design goals for StableHLO. This is a fancy way of saying that we want StableHLO to work very well with a variety of frameworks and hardware, and not having an opinion on specific runtimes or compilers makes this a bit easier.
