### ISSUE TITLE
Add type inference for SelectAndScatterOp

### ISSUE THREAD

**Issue by sdasgup3** [openxla/stablehlo#703]
### Request description

There is [inferSelectAndScatterOpReturnType](https://github.com/openxla/stablehlo/blob/ce4b89e796e44685892c67d0c3f0e6243505bd13/stablehlo/dialect/StablehloOps.cpp#L3946) but it's not hooked into the ODS.

**Comment by zhouxin913** [comment]
Hi @sdasgup3 , this looks duplicated with https://github.com/openxla/stablehlo/issues/212

**Comment by sdasgup3** [comment]
Thanks! let me close this.

superseded by https://github.com/openxla/stablehlo/issues/212.
