### ISSUE TITLE
Create an openxla.org@ account to host shareable documents

### ISSUE THREAD

**Issue by sdasgup3** [openxla/stablehlo#735]
### Request description

One immediate candidate to share would be the raw editable slide deck for creating specification images.

**Comment by burmako** [comment]
Another use case is sharing our spreadsheet with StableHLO ops, their categorization, etc. This could also potentially supersede status.md (although one benefit of status.md is that it's stored together with code, so it's harder to forget to update it).

**Comment by bhack** [comment]
> This could also potentially supersede status.md (although one benefit of status.md is that it's stored together with code, so it's harder to forget to update it).

https://github.com/openxla/stablehlo/issues/355

**Comment by theadactyl** [comment]
This has been created here: https://drive.google.com/corp/drive/folders/1617UbkYMZd-3PZB6Mx1AQe1xgeSQkP47, linked to in the /community repo: https://github.com/openxla/community
