### ISSUE TITLE
Update MHLO .td file to link to StableHLO spec

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#775]
We should probably directly copy/paste descriptions of already specced StableHLO ops from StableHLO's .td to MHLO's td.

**Comment by zhouxin913** [comment]
Update: Remain unassigned with low priority in favor of complete Spec work.
Open question: we may address all of these in bulk, or update the corresponding doc when implementing the interpreter op by op.

**Comment by burmako** [comment]
I think addressing in bulk would be easier because otherwise this becomes a recurring action items that authors and reviewers need to not forget. I definitely felt that when had to update StablehloOps.td in every spec PR in Q4.

**Comment by burmako** [comment]
Implemented in https://github.com/tensorflow/mlir-hlo/commit/d4f40974fe47f0ce7b5b03ac4ee1d6b1bc77d3ba.
