### ISSUE TITLE
Figure out what to do with unregistered attributes in VHLO

### ISSUE THREAD

**Issue by GleasonK** [openxla/stablehlo#784]
### Request description

There are use cases for unregistered attributes. There are two possible approaches:

1. A versioned allow-list of unregistered attributes.
2. Allow unregistered attributes as long as their values are representable in VHLO at the target version.

Currently (2) is implemented by #736.

**Comment by burmako** [comment]
See https://github.com/openxla/stablehlo/issues/744 for a relevant data point: the list of unregistered attributes used by JAX.

**Comment by GleasonK** [comment]
Our current plan is to allow unregistered attributes in the v0.9 release, which has 1mo forward/backward compatibility.

Prior to the v1.0 long-term compatibility guarantees we aim to understand the use cases for unregistered attributes and make a decision on whether they should be permitted or not. Ideally, the use cases for unregistered attributes should be natively supported in StableHLO. This follow-up exploration is tracked by #1070.
