### ISSUE TITLE
Nonconforming syntax in multiple markdown files

### ISSUE THREAD

**Issue by scottamain** [openxla/stablehlo#792]
### What happened?

Although some MD parsers are pretty forgiving (including GitHub's), the current markdown files in stablehlo include a variety of syntax errors that do not conform to the basic [MD syntax rules](https://daringfireball.net/projects/markdown/syntax). Examples include improper indentation for lists, unescaped asterisks signs (meant for bold or italic text), and missing blank lines between headings and paragraphs.

We should follow traditional MD syntax rules to ensure well-structured files that are easy to read, use an agreed-upon structure that can be tested, and that are compatible with more than one MD parser.

The simplest solution is to [markdownlint](https://github.com/markdownlint/markdownlint) and fix various syntax and style issues. 

We can submit fixes for individual files, and make exceptions as appropriate because this tool allows you to disable certain rules in the linter. Then, once the files are cleaned up, we should enable a GitHub Action to run markdownlint on all new pull requests with .md files so we can avoid re-introduction of syntax errors.

**Comment by burmako** [comment]
@scottamain Thank you for looking into this! This will be a nice improvement to the state of the art. We had prior discussions about Markdown linting but haven't had the time to follow up yet.

**Comment by burmako** [comment]
Reopening the ticket because #793 said that it only partially fixes it.

**Comment by GleasonK** [comment]
Not sure if this lint has been run on the `rfcs/` directory as well? I didn't see the Compatibility RFC in #793, and I'm doubtful that I used perfect MD syntax all the way through.

Here are [all md files in the repo](https://github.com/openxla/stablehlo/search?q=filename%3A.md).

**Comment by scottamain** [comment]
Hehe, yeah @GleasonK I didn't do the rfc files in the first CL just to keep my first PR simple. I'm sure you saw I've now cleaned those ones as well.

I think there's just two items remaining before closing this issue (in order):
1. Fix all lint errors in spec.md. I'm happy to do this but I don't want to cause confusing merge conflicts for others because this appears to be a fairly active document. @burmako Should we wait a little longer for this?
2. Enable the GitHub Action to run markdownlint on all .md file PRs.

**Comment by GleasonK** [comment]
> Should we wait a little longer for this?

Spoke with Eugene, totally fine to cause merge conflicts. There is only one open PR touching spec now, which makes this a good time to make that change. That plan sounds good to me.

Got the script running locally, looks like its only spec:

```
$ ./build_tools/github_actions/lint_markdown.sh "**/*.md" 2>&1 | grep -v spec
<no output, all failures are in spec.md>
```

**Comment by burmako** [comment]
Given that we have a CI job now which lints markdown files, I think we can close this ticket.
