### ISSUE TITLE
Handle bounds in `DynamicUpdateSliceOp`shape function

### ISSUE THREAD

**Issue by sdasgup3** [openxla/stablehlo#799]

**Comment by sdasgup3** [comment]
From (C3) @ https://github.com/openxla/stablehlo/blob/main/docs/spec.md#constraints-29 
shape of result is same as that of the operand. 

From
https://github.com/openxla/stablehlo/blob/93b3300d1ca7605b31fdbbd2a7fd959677d17563/stablehlo/dialect/TypeInference.cpp#L1390

we can see that the bounds in operand are already getting propagated to result. So, IMO, there is nothing to be done for this op.

**Comment by zhouxin913** [comment]
> From (C3) @ https://github.com/openxla/stablehlo/blob/main/docs/spec.md#constraints-29 shape of result is same as that of the operand.
> 
> From
> 
> https://github.com/openxla/stablehlo/blob/93b3300d1ca7605b31fdbbd2a7fd959677d17563/stablehlo/dialect/TypeInference.cpp#L1390
> 
> we can see that the bounds in operand are already getting propagated to result. So, IMO, there is nothing more to be done for this op.

LGTM, and please let Smit review as well. Thanks!

**Comment by sdasgup3** [comment]
@smit-hinsu Can you please review the observation as well?

**Comment by smit-hinsu** [comment]
We need to change it to the following to propagate the encoding?

inferredReturnShapes.emplace_back(operandType.getShape(),
                                      operandType.getElementType(), operandType.getEncoding());
