### ISSUE TITLE
Handle bounds in `OptimizationBarrierOp`shape function

### ISSUE THREAD

**Issue by sdasgup3** [openxla/stablehlo#806]

**Comment by smit-hinsu** [comment]
This op propagates input shapes so automatically already handled.
https://github.com/openxla/stablehlo/blob/fb65c58bed2efdad23ad6ea7109ee5500babfba5/stablehlo/dialect/TypeInference.cpp#L1497

**Comment by sdasgup3** [comment]
Thanks for the finding! Let us close this.
