### ISSUE TITLE
Move shape functions with Enums

### ISSUE THREAD

**Issue by zhouxin913** [openxla/stablehlo#830]
Leftover from https://github.com/openxla/stablehlo/pull/825.

FftOp::inferReturnTypeComponents(): has FftType from StablehloEnums.td
RngOp::verify(): hasRngDistribution from StablehloEnums.td

**Comment by burmako** [comment]
How about we turn enums into a bunch of boolean parameters, similarly to what we've done in [inferTriangularSolveOp](https://github.com/openxla/stablehlo/blob/efbc09992344bd5934e06a46b679d355aba8f6e9/stablehlo/dialect/TypeInference.h#L229-L232)?

**Comment by zhouxin913** [comment]
> How about we turn enums into a bunch of boolean parameters, similarly to what we've done in [inferTriangularSolveOp](https://github.com/openxla/stablehlo/blob/efbc09992344bd5934e06a46b679d355aba8f6e9/stablehlo/dialect/TypeInference.h#L229-L232)?

Good suggestion!

**Comment by burmako** [comment]
I've just noticed that there's still `rngInferReturnTypeComponents` still lives in StablehloOps.cpp. Let's move it to TypeInference.h as well.
