### ISSUE TITLE
Move verifier with TokenType

### ISSUE THREAD

**Issue by zhouxin913** [openxla/stablehlo#831]
Leftover from https://github.com/openxla/stablehlo/pull/825.

InfeedOp::verify()
RecvOp::verify()

both has TokenType defined in StablehloOps.h

**Comment by burmako** [comment]
There is already a mechanism to deal with token types. E.g. PTAL at [inferAfterAllOp](https://github.com/openxla/stablehlo/blob/efbc09992344bd5934e06a46b679d355aba8f6e9/stablehlo/dialect/TypeInference.cpp#L1293-L1298).
