### ISSUE TITLE
Move *DimensionSizeOp::verify()/infer() to TypeInference.h

### ISSUE THREAD

**Issue by zhouxin913** [openxla/stablehlo#832]
Leftover from https://github.com/openxla/stablehlo/pull/825.

SetDimensionSizeOp::verify()
GetDimensionSizeOp::verify()
SetDimensionSizeOp::inferReturnTypes()

Wait Spec for clear verification of these ops.

**Comment by burmako** [comment]
"Wait Spec for clear verification of these ops". I think we can already move verifiers / shape functions to be shared with MHLO without waiting for speccing them. Also, GetDimensionSizeOp already has a spec.

**Comment by zhouxin913** [comment]
Other integration issues were prioritized in last few weeks. Plan to finish this within next 1~2 weeks.
