### ISSUE TITLE
Think what to do with supporting -1 in GatherOp::slice_sizes

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#914]
Some MHLO tests depend on the following logic in `inferGatherOp`:

```
  auto getSliceDim = [&sliceSizes](int64_t index) -> int64_t {
    return sliceSizes.getValues<int64_t>()[index] == -1
               ? ShapedType::kDynamic
               : sliceSizes.getValues<int64_t>()[index];
  };
```

This is not something that we support in `inferGatherOp` at the moment, so at the moment, we carry this patch around in https://github.com/tensorflow/tensorflow/blob/master/third_party/stablehlo/temporary.patch. Would be good to clean this up in the near future.

**Comment by burmako** [comment]
#886 is a draft PR that's aiming to work this out.

**Comment by zhouxin913** [comment]
This done in MHLO side by aligning its code same as StableHLO
```
auto getSliceDim = [&sliceSizes](int64_t index) -> int64_t {
    return sliceSizes.getValues<int64_t>()[index];
  };
```
when a upstream op converting to mhlo ops with -1 in slice_sizes , it converts to `dynamis_gather` instead of `gather`. Thus the existence of -1 is gone in generated mhlo.
