### ISSUE TITLE
Add AllTypesMatch/AllShapesMatch Trait to SelectAndScatterOp

### ISSUE THREAD

**Issue by ghpvnist** [openxla/stablehlo#934]
SelectAndScatterOp (C12) restricts that operand and result types are the same. We should consider adding the AllTypesMatch/AllShapesMatch Trait to enforce this in the td file.

See [#917](https://github.com/openxla/stablehlo/pull/917#pullrequestreview-1248685484) for related PR on bounded dynamism.

**Comment by ghpvnist** [comment]
After further look, adding these traits do not work when we need compatible types, hence why #900 is migrating away from them.

**Comment by smit-hinsu** [comment]
I don't know our plan for binary ops but some trait like AllTypesCompatible and AllShapesCompatible could be an option for all these ops.
