### ISSUE TITLE
Decide on a policy for dealing with IEEE-754 exceptions

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#95]
The current thinking in spec_draft.md involves floating-point ops following IEEE-754 semantics. What does this mean as far as exception handling goes? As suggested offline by @joker-eph, [the LLVM Language Reference Manual](https://llvm.org/docs/LangRef.html) provides one way of handling this:

> ### Floating-Point Environment
>
>The default LLVM floating-point environment assumes that floating-point instructions do not have side effects. Results assume the round-to-nearest rounding mode. No floating-point exception state is maintained in this environment. Therefore, there is no attempt to create or preserve invalid operation (SNaN) or division-by-zero exceptions.
>
> The benefit of this exception-free assumption is that floating-point operations may be speculated freely without any other fast-math relaxations to the floating-point model.
>
> Code that requires different behavior than this should use the [Constrained Floating-Point Intrinsics](https://llvm.org/docs/LangRef.html#constrainedfp).

Here's how this floating-point environment is then used to defined floating-point operations in LLVM.

> ### ‘fadd’ Instruction
>
> Syntax:
> <result> = fadd [fast-math flags]* <ty> <op1>, <op2>   ; yields ty:result
>
> Semantics:
> The value produced is the floating-point sum of the two operands. This instruction is assumed to execute in the default [floating-point environment](https://llvm.org/docs/LangRef.html#floatenv). This instruction can also take any number of [fast-math flags](https://llvm.org/docs/LangRef.html#fastmath), which are optimization hints to enable otherwise unsafe floating-point optimizations:

**Comment by sdasgup3** [comment]
My proposal is to comply with the HLO's stance of no-exception-handling, i.e.,  no exception state maintained in the execution environment.
