### ISSUE TITLE
Decide on a policy for specifying numeric precision

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#96]
In #86, we've gotten into a discussion of what it means exactly to perform a cosine operation. Or, more precisely, what kind of precision with respect to an ideal mathematical result are we talking about? Initially, the policy could be as simple as "Numeric precision is implementation-defined", but I think that eventually we could work out something more specific.

**Comment by sdasgup3** [comment]
A few pointers:

For implementing transcendental operations, we plan to use use std variants, thus exploring them could give us some hint on the precision guarantees we can make.  One option could be to say that the numeric precision is the same as offered by the std variants. 

Please note that  std variants use GNU libm which looks system dependent. 

```
git clone git://sourceware.org/git/glibc.git
find sysdeps -name *cos.c
```

**Comment by ghpvnist** [comment]
Section 9.2 of IEEE-754 has a list of “***recommended*** correctly rounded functions”. Following the IEEE-754 standard does not guarantee correctly rounded to 0.5 ulp (rounded exact to the last bit). Other std functions in C++ follow the standard by using double, thus any calculations involving floats should be cast to double.

`f64` has 53 bits of mantissa bits (52 explicit and 1 implied bit), which allows $2^{-53}\approx 1.11*10^{-16}$, or 15-17 significant decimal digits of precision. If we really want our best attempt at conforming to the standard with more than 17 digits of precision for `f64` or allow accumulation of results for single (pow, which does log of the exponent number of multiplies) or multiple operations, using `long double` is an option to consider, noting that different variants of the compiler has varying bits of storage for `long double`.

Related links:
https://en.wikipedia.org/wiki/Double-precision_floating-point_format#cite_note-whyieee-1
https://stackoverflow.com/questions/69380549/is-cosx-required-to-return-identical-values-in-different-c-implementations-t
https://stackoverflow.com/questions/4317988/ieee-754-floating-point-precision-how-much-error-is-allowed

**Comment by sdasgup3** [comment]
As pointed that these transcendental functions are listed as “recommended correctly rounded functions”. Being a recommendation,  a conforming implementation can chose to move away from "correct rounding"  (rounding an "infinitely precise" result of the operation to the closest representable floating-point number) recommendation.  In our case, it allows to accept any reasonable precision provided by the existing implementations of transcendental functions, which ranges from approximating the values from Taylor's series to mapping to a [hardware instruction](https://www.felixcloutier.com/x86/fcos)

**Comment by joker-eph** [comment]
Can you also look for reference into other standards like Metal or DirectX for example?

**Comment by burmako** [comment]
"Having said that my proposal is to leave the precision guarantees to implementations". I agree, as far as the spec draft goes. At the moment, we're basically documenting the current behavior of HLO, so I think it's fine to keep following the "Numeric precision is implementation-defined" formula. 

During spec review, we should revisit this, in case this turns out to be a blocker for someone. Otherwise, we can leave defining more precise numeric guarantees to post-1.0.
